OpenGL updates
inviwo/inviwo pull request #1078
Opened 2020-12-04 13:51 UTC by petersteneteg

2020-12-05 07:10 UTC, ResearchDaniel requested changes
Nice! Some minor comments

2020-12-05 07:10 UTC, ResearchDaniel commented on include/inviwo/core/util/moveonlyvalue.h
> + * optional will be left empty
Typo, moving

2020-12-05 07:10 UTC, ResearchDaniel commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +     */
Typo, if

2020-12-05 07:10 UTC, ResearchDaniel commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +    bool checkStatus() const;
Should there be an option for logging? 
Or separate into two. One for checking status and one for checking and logging?

2020-12-05 07:10 UTC, ResearchDaniel commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +    static GLuint maxColorattachments();
Duplicate of getMaxColorAttachments?
Also, camel case for Attachments

2020-12-05 07:10 UTC, ResearchDaniel commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +    void activateBuffer(ImageType imageType = ImageType::AllLayers);
Should return the state

2020-12-05 07:10 UTC, ResearchDaniel commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +     * interpolation. If some layers are not attached to the FBO they will be copies using PBO
Typo, copied

2020-12-05 07:10 UTC, ResearchDaniel commented on modules/opengl/src/image/imagegl.cpp
> +    , colorAttachmentIDs_{}
Could initialize these in the header to avoid duplicating code in the constructors?

2020-12-05 19:48 UTC, petersteneteg commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +    void activateBuffer(ImageType imageType = ImageType::AllLayers);
This one does not save the state only the new active one does that. In most cases it is not needed. But I see i made a copy paste misstake in the doc...

2020-12-05 19:52 UTC, petersteneteg commented on modules/opengl/src/image/imagegl.cpp
> +    , colorAttachmentIDs_{}
Im not too fond of initialising stuff in the header. It leaks implementation details into the header, it means I have to recompile when ever I change something, and it separates the constructions code into two different places. But maybe I will come around at some point.

2020-12-06 13:21 UTC, ResearchDaniel commented on modules/opengl/src/image/imagegl.cpp
> +    , colorAttachmentIDs_{}
Yeah, I guess it has its pros and cons. Does not matter too much

2020-12-06 13:22 UTC, ResearchDaniel commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +    void activateBuffer(ImageType imageType = ImageType::AllLayers);
I see. Perhaps we could make a note on which one should be used an for which cases

2020-12-07 13:37 UTC, petersteneteg commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +    bool checkStatus() const;
true... will refactor more

2020-12-07 15:50 UTC, ResearchDaniel approved these changes, later dismissed

2020-12-07 16:43 UTC, martinfalk approved these changes, later dismissed
nice job with cleaning up the FBO states. Some typos...

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> + * detachment of textures to the framebuffer. It Also keeps track of all attached texture ids. The
typos, 
"attachment"/"detachment" -> attaching/detaching 
"Also" -> "also"
"wapper" -> "wrapper"

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +     * @brief Attach a 3D Texture to the framebuffer
maybe mention that "use `gl_Layer` in the geometry shader to set target z slice."

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +     */
mention `gl_Layer`?

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +     * @param layer index of the layer to attach
z layer?

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +     * @param layer index of the layer to attach
z layer?

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/buffer/framebufferobject.h
> +     * @brief Check if there is any color attachments
either "is ... attachment" or "are ... attachments"

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/image/imagegl.h
> + * @brief OpenGL representation of a Image as a OpenGL framebuffer
typo "of _an_ Image"

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +     * @brief Store the current "state" and active the FBO.
"activate"

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +     * @brief Copies @p source into this using Blitting and PBOs if needed.
into this? suggestion "into this ImageGL" or "into this instance"

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +     * Does not care about aspect ratios, copies the source image into the this using "nearest"
typo "into the this"

2020-12-07 16:43 UTC, martinfalk commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +     * @return true
always?

2020-12-09 13:31 UTC, petersteneteg commented on modules/opengl/include/modules/opengl/image/imagegl.h
> +     * @return true
yes

2020-12-09 14:40 UTC, martinfalk approved these changes

2020-12-09 14:40 UTC, merged