Feature/core fixes
inviwo/inviwo pull request #1104
Opened 2021-01-27 10:19 UTC by petersteneteg

2021-01-27 12:49 UTC, martinfalk requested changes

2021-01-27 12:49 UTC, martinfalk commented on include/inviwo/core/processors/processor.h
> +    NameDispatcherHandle onIdentifierChange(
maybe add comment regarding arguments of std::function. Assuming "prev" and "new" identifier?

2021-01-27 12:49 UTC, martinfalk commented on include/inviwo/core/processors/processor.h
> +        std::function<void(std::string_view, std::string_view)>);
comment re std::function

2021-01-27 12:49 UTC, martinfalk commented on modules/qtwidgets/src/processors/processordockwidgetqt.cpp
> +    setWindowTitle(QString::fromStdString(processor_->getDisplayName()));
use `utilqt::fromQString`
Note that the display name is not necessarily unique!

2021-01-27 12:49 UTC, martinfalk commented on modules/qtwidgets/src/tf/tfpropertydialog.cpp
> +        "Transfer Function Editor - " + property_->getDisplayName() + " (" + processorName + ")";
use fmt::format?

2021-01-27 15:40 UTC, martinfalk approved these changes

2021-01-27 17:05 UTC, merged

2021-01-27 18:41 UTC, ResearchDaniel reviewed
How are the added callbacks removed?

2021-01-28 07:30 UTC, petersteneteg commented
you just drop the handle