Feature/splitter
inviwo/inviwo pull request #1149
Opened 2021-04-21 16:15 UTC by martinfalk

* refactoring of the splitter handle from `SplitImage` into a separate renderer and property
* support to change the mouse cursor in mouse events, for example during picking or hovering

https://user-images.githubusercontent.com/9251300/115586958-6a478700-a2cd-11eb-9b24-6377a08c8a55.mp4

2021-04-24 09:06 UTC, petersteneteg requested changes

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/glsl/splitter.geom
> +void main() {
alot of this has to be duplicate from other line renderers? should it not be shared?

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/glsl/splitter.vert
> +void main() {}
I think passing in a line for each splitter to be drawn would be a better method. Then multiple splitters could be drawn at the same time. Or make trafo a list and loop over it, but that seems strange...

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/glsl/splitter.geom
> +void main() {
also is all this needed here since it will only be 1 line and it will be axis alined?

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/glsl/splittertriangle.geom
> +    const float sqrt3half = 0.8660254037844386;
could use this one for the lines to...

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/include/modules/basegl/rendering/splitterrenderer.h
> +    SplitterRenderer& operator=(SplitterRenderer&& rhs) = default;
so you allow copy construct but not move construct, and allow move assign but not copy assign? seems very strange

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/include/modules/basegl/rendering/splitterrenderer.h
> +    SplitterRenderer(const SplitterSettings& settings, Processor* processor);
is there a good reason for passing in the settings here and not in the render call?
We might have done it like this before. But Im not convinced it is the best way. The semantics of how the settings will he handled get a bit unclear? will the renderer copy the settings and store them. So you have to recreate the renderer to change a setting. Or does it store a reference to the settings, meaning you have to make sure to keep the settings alive while the renderer is a live.

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/include/modules/basegl/rendering/splitterrenderer.h
> +    SplitterRenderer(const SplitterSettings& settings, Processor* processor);
What is the processor needed for?

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/properties/splitterproperty.cpp
> +    length_.setSemantics(PropertySemantics("SpinBox"));
move to constructor. need to make it default otherwise

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/properties/splitterproperty.cpp
> +    style_.setSelectedValue(style);
set as default, or move to constructor...

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +    mesh_ = std::make_shared<Mesh>(DrawType::Points, ConnectivityType::None);
Why a shared_ptr, just us a Mesh

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +    , pickingMapper_(processor, 1, [&](PickingEvent* e) { handlePickingEvent(e); }) {
ahh that's where the processor is used. We should change the picking at some point to remove that convoluted dependency.

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +    }
```suggestion
const auto [lineWidth, handleWidth, drawHandle, drawBorder] = [&]() -> std::tuple<float, float, bool, bool> {
    const float width = settings_.get().getWidth();
    switch (style) {
        case splitter::Style::Handle:
            return {width / 3.0f, width, true, true};
        case splitter::Style::Divider:
            return {widtf, width * 0.6f, true, false};
        case splitter::Style::Line:
            return {width, 0.0f, false, false};
        case splitter::Style::Invisible:
            return {0.0f, 0.0f, true, false};
        default:
            return {0.0f, 0.0f, true, false};
    }
}();
```

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +    m[3] = vec4(pos * 2.0f - 1.0f, -1.0f, 0.0f, 1.0f);
make into a function with a name to explain what it is...

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +            // start hover
```suggestion
```

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +            // end hover
```suggestion
```

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +        auto mouseEvent = e->getEventAs<MouseEvent>();
```suggestion
    if (auto mouseEvent = e->getEventAs<MouseEvent>()) {
```

2021-04-24 09:06 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +        processor_->invalidate(InvalidationLevel::InvalidOutput);
might be better with a callback here similar to moveAction

2021-04-26 09:01 UTC, martinfalk commented on modules/basegl/glsl/splittertriangle.geom
> +    const float sqrt3half = 0.8660254037844386;
what do you mean?

2021-04-26 09:03 UTC, martinfalk commented on modules/basegl/include/modules/basegl/rendering/splitterrenderer.h
> +    SplitterRenderer(const SplitterSettings& settings, Processor* processor);
The settings are kept via a reference similar to the AxisRenderer and its settings.

The processor is required for the picking mapper inside the renderer needed to handle interaction event.

2021-04-26 09:04 UTC, martinfalk commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +    }
looks neater.

2021-04-26 09:09 UTC, martinfalk commented on modules/basegl/include/modules/basegl/rendering/splitterrenderer.h
> +    SplitterRenderer(const SplitterSettings& settings, Processor* processor);
Multiple splitters will reuse the same settings.

2021-04-26 11:00 UTC, petersteneteg commented on modules/basegl/glsl/splittertriangle.geom
> +    const float sqrt3half = 0.8660254037844386;
That shader, the splitter line also only need a quad, or?

2021-04-26 11:07 UTC, martinfalk commented on modules/basegl/glsl/splittertriangle.geom
> +    const float sqrt3half = 0.8660254037844386;
A single point becomes two triangles. But I guess the line shader could be simplified, since there are only orthogonal lines.

2021-04-26 11:07 UTC, martinfalk commented on modules/basegl/include/modules/basegl/rendering/splitterrenderer.h
> +    SplitterRenderer& operator=(SplitterRenderer&& rhs) = default;
inspired by AxisRenderer, I think.

2021-04-26 13:18 UTC, martinfalk commented on modules/basegl/glsl/splitter.geom
> +void main() {
The reason is to render geometry-less lines in normalized device coordinates (transformation contains rotation and position). This avoids recreating the mesh when extending it for multiple splitters.

2021-04-26 13:19 UTC, martinfalk commented on modules/basegl/glsl/splitter.vert
> +void main() {}
trafo list is possible in the geometry shader. The main idea was to avoid recreating the mesh.

2021-04-26 13:23 UTC, martinfalk commented on modules/basegl/include/modules/basegl/rendering/splitterrenderer.h
> +    SplitterRenderer& operator=(SplitterRenderer&& rhs) = default;
move constructor should be default.
Picking mapper prevents copy-assignment

2021-04-26 13:27 UTC, martinfalk commented on modules/basegl/src/properties/splitterproperty.cpp
> +    style_.setSelectedValue(style);
not possible to move to constructor since that one only uses an index to select the initial option.

2021-04-26 13:32 UTC, martinfalk commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +    , pickingMapper_(processor, 1, [&](PickingEvent* e) { handlePickingEvent(e); }) {
agree. Also annoying: the picking mapper holds a processor, but no way to query it. Hence the additional `processor_` member.

2021-04-27 08:41 UTC, petersteneteg commented on modules/basegl/src/properties/splitterproperty.cpp
> +    style_.setSelectedValue(style);
just use a lambda.

2021-04-27 08:41 UTC, petersteneteg commented on modules/basegl/src/properties/splitterproperty.cpp
> +    style_.setSelectedValue(style);
or add the constructor

2021-04-27 08:45 UTC, petersteneteg commented on modules/basegl/src/rendering/splitterrenderer.cpp
> +    , pickingMapper_(processor, 1, [&](PickingEvent* e) { handlePickingEvent(e); }) {
well since you can't query it is easier to remove at some point...

2021-04-27 09:12 UTC, petersteneteg approved these changes

2021-04-28 08:14 UTC, merged