Feature/python additions
inviwo/inviwo pull request #1173
Opened 2021-08-24 11:27 UTC by petersteneteg

Fixes an issue with the OpenGL format not being set when staring the inviwopyapp.
Added implicit conversions from python list to glm vec types.
Added a implementation of a ipython event loop hook for the inviwopyapp

2021-08-24 13:12 UTC, ResearchDaniel requested changes
Some minor de/comment issues that need to be fixed

2021-08-24 13:12 UTC, ResearchDaniel commented on apps/inviwopyapp/inviwo.py
> +    #app.network.Canvas.snapshot("snapshot.png")
Decomment

2021-08-24 13:12 UTC, ResearchDaniel commented on apps/inviwopyapp/inviwo.py
> +    # addIpythonGuiHook(app)
Decomment or remove

2021-08-27 11:48 UTC, martinfalk submitted a review, later dismissed

2021-08-27 11:48 UTC, martinfalk commented on apps/inviwopyapp/inviwo.py
> +
fix newlines at end of file

2021-08-27 14:42 UTC, petersteneteg commented on apps/inviwopyapp/inviwo.py
> +    # addIpythonGuiHook(app)
working on adding some cli arguments to the script...

2021-09-01 09:04 UTC, ResearchDaniel submitted a review, later dismissed

2021-09-01 09:04 UTC, ResearchDaniel commented on include/inviwo/core/util/unindent.h
> + * The first indented line determines the amount of indentation to remove, If any of the following
Typos. 
remove, -> remove.
as less indentation -> are less than indentation

2021-09-01 09:04 UTC, ResearchDaniel commented on include/inviwo/core/util/unindent.h
> + * The first indented line determines the amount of indentation to remove, If any of the following
Same typos as above

2021-09-01 12:03 UTC, ResearchDaniel approved these changes

2021-09-01 13:09 UTC, martinfalk approved these changes

2021-09-01 13:09 UTC, martinfalk commented on apps/inviwopyapp/inviwo.py
> +    If python can't find the i`inviwopy` module use the '--libdir' CLI argument to pass
special syntax for `i'inviwopy'`?

2021-09-01 13:09 UTC, martinfalk commented on include/inviwo/core/util/unindent.h
> + * Copy the chard of the string (being, end) to `out` skipping the leading indentation of each line
typo `chars`

2021-09-01 13:12 UTC, merged