Feature/brushing highlight
inviwo/inviwo pull request #1206
Opened 2021-10-08 15:00 UTC by martinfalk

Highlight events for brushing and linking can be used to temporarily highlight objects, for example on hovering. Example implementation added to scatter plot and parallel coordinate plot. 

Completely reworked Brushing and Linking. Managers are now owned by BrushingAndLinkingInports and BrushingAndLinkingOutports. Brushing actions are propagated directly between managers without needing events.

2021-10-08 20:08 UTC, petersteneteg requested changes
Nice work, some minor comments

2021-10-08 20:08 UTC, petersteneteg commented on CHANGELOG.md
> +## 2021-10-06 Updated Brushing & Linking
we want pictures :)

2021-10-08 20:08 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/indexlist.h
>  #include <unordered_set>
remove

2021-10-08 20:08 UTC, petersteneteg commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +    std::unordered_map<std::string, BitSet> map;
using IdentifiedDeserializer I think you could do this in one step...

2021-10-08 20:08 UTC, petersteneteg commented on modules/brushingandlinking/src/ports/brushingandlinkingports.cpp
> +        sendHighlightEvent(highlightCache_);
this call probably happens after the B&L manager is deserialized, would it make more sense to serialize all the state in each inport?

2021-10-08 20:08 UTC, petersteneteg commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +        } else if (dynamic_cast<HighlightEvent*>(event)) {
we have special tag in the event to avoid having to dynamic_cast here...

2021-10-08 20:08 UTC, petersteneteg commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +                glDrawElements(
if this can also be a set of lines just as will move it into the loop above? or are you trying to avoid the partition here?

2021-10-08 20:08 UTC, petersteneteg commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +            BitSet b;
can't you add the indices to the constructor?

2021-10-08 20:08 UTC, petersteneteg commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        selection.flip(indexCol[id]);
nice!

2021-10-09 08:29 UTC, ResearchDaniel requested changes
Nice work! There is a todo that should be fixed and some refactoring related to extracting indices from a data frame that would be good to do.


A general comment/question about brushing and linking ids:
I might be wrong, but it seems as if the id is sometimes used as a row/item index and sometimes mapped through the IndexColumn. Especially when used with picking. We probably need to double check that we are consistent and make it easy and/or clear how to use to the “right” way. This might not be related to this PR though

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    BitSet filterCache_;
Perhaps not part of this PR, but these should have been private from the beginning because they must be changed through the sendXEvent functions?

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    filtered_.deserialize(d, port);  // TODO: check for double invalidation caused by filtered_
Don’t forget to fix

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +        "ports", indicesBySource_, "indices", {},
Why ports here?

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    void sendHighlightEvent(const BitSet& indices);
Probably a good idea to state that these should be sent when hovering

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
>      IndexList filtered_;  // Use IndexList to be able to remove filtered rows on port disconnection
Not completely related to this PR, but should we not treat all in the same way

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/plottinggl/include/modules/plottinggl/plotters/persistencediagramplotgl.h
> +    BitSet selectedIndices_;
Not part of PR, but would be nice if we could avoid having a copy of the state and use the brushing directly.

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/plottinggl/include/modules/plottinggl/plotters/scatterplotgl.h
>      std::vector<bool> filtered_;
Should not these be replaced with BitSet?

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/plottinggl/src/plotters/scatterplotgl.cpp
> +        glDrawElements(GL_POINTS, highlighted_.cardinality(), highlightIndexGL_.getFormatType(),
Is it possible to upload the bitsets and do the logic in the vertex shader?
Would simplify the code a lot I think

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        if (selected) brushedID.add(index);
Not really selected…

2021-10-09 08:29 UTC, ResearchDaniel commented on modules/plottinggl/src/processors/scatterplotprocessor.cpp
> +                auto iCol = dataFramePort_.getData()->getIndexColumn();
Finding the indices is a pretty common operation. Should it perhaps be extracted to the data frame  or something?

2021-10-09 11:51 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    void sendHighlightEvent(const BitSet& indices);
I would not say Should more like could or that it's common. There might be other scenarios where it might be useful too

2021-10-09 11:52 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
>      IndexList filtered_;  // Use IndexList to be able to remove filtered rows on port disconnection
We can't do that since they have different semantics

2021-10-09 11:53 UTC, petersteneteg commented on modules/plottinggl/include/modules/plottinggl/plotters/persistencediagramplotgl.h
> +    BitSet selectedIndices_;
Can one not just direct access the cache in the inport?

2021-10-09 11:54 UTC, petersteneteg commented on modules/plottinggl/src/plotters/scatterplotgl.cpp
> +        glDrawElements(GL_POINTS, highlighted_.cardinality(), highlightIndexGL_.getFormatType(),
The bitsets are compressed, so unpacking them in the shader is probably not that easy, or efficient

2021-10-10 11:26 UTC, martinfalk commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +        "ports", indicesBySource_, "indices", {},
for the same reason they are stored in the map of this IndexList. This has to do with how filtering works. A selection consists of just the indices set in the latest selection event. Filtering, however, restricts indices and two filter events might overlap.
For example: indices 1 to 10
- filter event A filters 1-5 (i.e. removes those indices)
- filter event B filter 3-6
This results in indices {7, .., 10} remaining.

If you now disconnect the port for event A, the filtered set should be {1, 2, 7-10}. Hence, we need to keep track of where a filter event came from. The actual filtered set is computed through a union of still active filter connections.

2021-10-10 11:26 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
>      IndexList filtered_;  // Use IndexList to be able to remove filtered rows on port disconnection
see comment above on filter events

2021-10-10 11:27 UTC, martinfalk commented on modules/plottinggl/include/modules/plottinggl/plotters/scatterplotgl.h
>      std::vector<bool> filtered_;
Different can of worms and independent of the brushing and linking mechanism.

2021-10-10 11:29 UTC, martinfalk commented on modules/plottinggl/src/plotters/scatterplotgl.cpp
> +        glDrawElements(GL_POINTS, highlighted_.cardinality(), highlightIndexGL_.getFormatType(),
@petersteneteg is correct, unless you plan to implement the decoding from CRoaring in shaders. One alternative would be to either encode the set bits as a bit mask (selected, filtered, highlighted) in a vertex buffer (requires mesh update on brushing event) or a Shader Storage Buffer Object (requires OpenGL 4.2 but the mesh doesn't need to be updated).

2021-10-10 11:29 UTC, martinfalk commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        if (selected) brushedID.add(index);
you could say it is a selected index. Open for name suggestions.

2021-10-10 11:32 UTC, martinfalk commented
> A general comment/question about brushing and linking ids:
I might be wrong, but it seems as if the id is sometimes used as a row/item index and sometimes mapped through the IndexColumn. Especially when used with picking. We probably need to double check that we are consistent and make it easy and/or clear how to use to the “right” way. This might not be related to this PR though

Not related but this is a general problem.  For example, things will go nasty once a dataframe is filtered and all of a sudden the row indices no longer match with the index column.

2021-10-10 12:43 UTC, petersteneteg commented
From a discussion we had:
> all the B&L events, could they just be one event/call with a Action {Filter, Select, Highlight} and a Target {Row, Column, Arb string}?

2021-10-10 14:06 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/indexlist.h
>  #include <unordered_set>
why? There is a BitSet member in the class.

2021-10-10 15:53 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/indexlist.h
>  #include <unordered_set>
He is referring to map/set :)

2021-10-10 16:37 UTC, ResearchDaniel commented on modules/plottinggl/include/modules/plottinggl/plotters/scatterplotgl.h
>      std::vector<bool> filtered_;
Ok

2021-10-10 18:52 UTC, ResearchDaniel commented on modules/plottinggl/src/plotters/scatterplotgl.cpp
> +        glDrawElements(GL_POINTS, highlighted_.cardinality(), highlightIndexGL_.getFormatType(),
ok, too bad

2021-10-10 18:52 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    void sendHighlightEvent(const BitSet& indices);
Agree

2021-10-10 18:55 UTC, ResearchDaniel commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        if (selected) brushedID.add(index);
filtered?

2021-10-15 14:58 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    BitSet filterCache_;
no longer applicable. Caches replaced with B&L managers.

2021-10-15 15:00 UTC, martinfalk commented on modules/plottinggl/include/modules/plottinggl/plotters/persistencediagramplotgl.h
> +    BitSet selectedIndices_;
Should be possible now after the refactoring.

2021-10-15 15:09 UTC, martinfalk commented on modules/plottinggl/src/processors/scatterplotprocessor.cpp
> +                auto iCol = dataFramePort_.getData()->getIndexColumn();
Needs more work, potentially a bidirectional map being part of the index column.

2021-10-16 12:15 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/brushingaction.h
> +    BrushingTarget() = default;
Hmm should this be allowed? should it default to Row?

2021-10-16 12:15 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/brushingaction.h
> +    }
why not just use the else case?

2021-10-16 12:15 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/brushingaction.h
> +    std::string target;
I would like to avoid having to copy this string around all the time seems expensive to me. Could use a std::shared_ptr<const std::string> instead, then you only have to create it one, and all copies will just copy the pointer not reallocating the string. Also you only have to compare the pointers to check for equality etc...

2021-10-16 12:16 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/brushingaction.h
> +    std::string target;
Humm maybe that last part is not true... you know they are equal if the pointers are the same, if they are nog you sill have to compare them :(

2021-10-16 12:18 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/brushingaction.h
> +    std::string target;
One way would be to have a static vector of week_ptr to all the targets, and check if a string matches an existing one... that way you would avoid any duplicates...

2021-10-18 11:42 UTC, ResearchDaniel requested changes
Very nice work!

**Some thoughts**

- BrushingTarget::Row may be confused with the row number, while it actually referes to the id in the IndexColumn. 
BrushingTarget::Index?
BrushingTarget::Id? 

- Do we want to be able to propagate information from the manager to the sources (e.g. for clearing)? Then it would be better to use a BrushingSource interface instead of a string. 

- For columns we are using the direct index, but not for rows. This is a bit inconsistent...

- Perhaps a too big design change now, but using a function interface instead of a Bitset for the brush interface could potentially save memory. For example: Each plot in a scattermatrix has its own selection/highlight/filter. In these cases it is not necessary to store the selection, just the the ranges associated with the two axes.



Only using IndexList would make the code clearer (avoid the overload in each std::visit call.

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +/*
Remove commented code

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +     * @param source   must be provided if action is equal to BrushingAction::Filter
source should always be provided in my opinion. Otherwise it will not be possible to do union/intersect between sources. 
Usually source == processor identifier?

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
Don’t we want to have one set per source so that we can do union/intersect/latest over the selection? At least do it if user wants union/intersect

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    [[deprecated("clearing filtered indices is no longer supported")]] void clearFiltered();
Add:
Use filter(…) with empty BitSet

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/indexlist.h
> +    using PortIndexMap = std::unordered_map<std::string, BitSet>;
SourceIndexMap

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/processors/brushingandlinkingprocessor.h
> -    ButtonProperty clearFilter_;
Not possible to clear filter anymore?
What does clearAll_ do in that case?

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +    indices_ = BitSet::fastUnion(bitsets);
We want options for this to cover all cases?

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +    if (indicesDirty_) {
This check is already done in update…

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +    if (indicesDirty_) {
Checked in update

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +    , clearAll_("clearAll", "Clear All", [&]() {
This is not all anymore

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +        outport_.getManager().clearSelected();
Is it possible to specify BrushingTarget::Row | BrushingTarget::Column

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +        throw Exception(fmt::format("Clearing indices for action '{}' is not supported", action),
Supporting this would mean that we propagate other types of information/actions with the manager. 
By delegating these tasks (clear) to the implementations connected to the brushing and linking we could more easily support the actions with cached sources (which might need to be all if we want to support union/intersect for select/highlight as well).
Could for example register an onClearRequest with the manager so that we can support clearing from the manager?

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +        throw Exception(fmt::format("Clearing indices for action '{}' is not supported", action),
On the other hand it might not be worth the effort to support such concepts?

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/dataframeqt/src/processors/dataframetable.cpp
> +            w->updateColumnSelection(brushLinkPort_.getSelectedIndices(BrushingTarget::Column));
Do you want to check for isModified for column/row?

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +                                      selectedLineWidth_};
Highlight width is same as selection?

2021-10-18 11:42 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +     * @param source   must be provided if action is equal to BrushingAction::Filter
Also, should we use an interface for source instead of a string?
That way the manager could communicate with the source to for example clear filter.

2021-10-18 12:38 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +     * @param source   must be provided if action is equal to BrushingAction::Filter
at the moment, selection and highlight are not requiring a source since they are replacing the currently selected indices. If that is going to change, then sure. But that is beyond the refactoring in this PR.

2021-10-18 12:39 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +     * @param source   must be provided if action is equal to BrushingAction::Filter
> Usually source == processor identifier?

If the action is propagated by a port, it is `port->getPath()` otherwise it could be anything. In case of the parallel coords, it uses the names of the axes.

2021-10-18 12:43 UTC, martinfalk commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
union/intersect for highlight and selection -> future PR

2021-10-18 12:45 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/processors/brushingandlinkingprocessor.h
> -    ButtonProperty clearFilter_;
"clear filter" in the manager will lead to an inconsistent state since the filter is still active in the source. Clear All will reset all selections but the filtered one.

2021-10-18 12:45 UTC, martinfalk commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +    indices_ = BitSet::fastUnion(bitsets);
future PR

2021-10-18 12:46 UTC, martinfalk commented on modules/brushingandlinking/src/datastructures/indexlist.cpp
> +    if (indicesDirty_) {
good catch

2021-10-18 12:47 UTC, martinfalk commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +    , clearAll_("clearAll", "Clear All", [&]() {
should it state "clear selection, highlight, column selection" instead? ;-)

2021-10-18 12:48 UTC, martinfalk commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +    , clearAll_("clearAll", "Clear All", [&]() {
renamed to `clearAllAbove_("clearAllAbove", "Clear All Above"`

2021-10-18 12:49 UTC, martinfalk commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +        outport_.getManager().clearSelected();
No, since targets are no flags.

2021-10-18 12:51 UTC, martinfalk commented on modules/dataframeqt/src/processors/dataframetable.cpp
> +            w->updateColumnSelection(brushLinkPort_.getSelectedIndices(BrushingTarget::Column));
The modified state does not differentiate between columns and rows. We could add that later if we think it is necessary.

2021-10-18 12:52 UTC, martinfalk commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +                                      selectedLineWidth_};
Yes, the difference being the color and the line rendered on top.

2021-10-18 13:03 UTC, martinfalk commented
> **Some thoughts**
> 
> * BrushingTarget::Row may be confused with the row number, while it actually referes to the id in the IndexColumn.
>   BrushingTarget::Index?
>   BrushingTarget::Id?

Decided to use row as being orthogonal to column and our brushing and linking often relies on a DataFrame as underlying data source.

> * For columns we are using the direct index, but not for rows. This is a bit inconsistent...

That is because we don't have a special mapping for columns besides their index. The current DataFrame implementation _always_ creates an index column even when creating an empty DataFrame (which cause other problems...). We might want to consider getting rid of the index column entirely. However, bear in mind that filtering a DataFrame and outputting a new one would affect those direct indices and thus breaking brushing and linking.

> * Do we want to be able to propagate information from the manager to the sources (e.g. for clearing)? Then it would be better to use a BrushingSource interface instead of a string.

Maybe in a follow-up PR.

> * Perhaps a too big design change now, but using a function interface instead of a Bitset for the brush interface could potentially save memory. For example: Each plot in a scattermatrix has its own selection/highlight/filter. In these cases it is not necessary to store the selection, just the the ranges associated with the two axes.

Agreed, using ranges instead of explicit index lists would change things quite a bit.

2021-10-18 13:04 UTC, ResearchDaniel commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +    , clearAll_("clearAll", "Clear All", [&]() {
I guess clear selection would be fine.

2021-10-18 13:04 UTC, ResearchDaniel commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +    , clearAll_("clearAll", "Clear All", [&]() {
Ah, that is the name of one of the above :D

2021-10-18 13:05 UTC, ResearchDaniel commented on modules/brushingandlinking/src/processors/brushingandlinkingprocessor.cpp
> +    , clearAll_("clearAll", "Clear All", [&]() {
Clear selections then :)

2021-10-19 10:42 UTC, petersteneteg requested changes
Nice work, nice we finally got this done! 
just some minor comments

2021-10-19 10:42 UTC, petersteneteg commented on CHANGELOG.md
> +**Update Note:** In case you are using `port.isChanged()` on a `BrushingAndLinkingInport`, you **must** replace this with one of the calls above. Otherwise your selection might no longer be updated.
what about the onChange callback is that also not usable anymore? Could we make them work? having both isModified and isChanged is a bit confusing...

2021-10-19 10:42 UTC, petersteneteg commented on include/inviwo/core/io/serialization/serializebase.h
> +               std::is_same_v<T, std::string> || std::is_same_v<T, std::string_view>;
Note: In principle we could use is_stream_insertable here, since we handle that on the deserialization side. 
But in principle we should also have something like has_unique_string_representation. Or support_iostream_roundtrip or something like that...

2021-10-19 10:42 UTC, petersteneteg commented on modules/basegl/include/modules/basegl/processors/sphererenderer.h
> -                                 [&](uint32_t i) { return selection.count(indexBuffer[i]) > 0; });
you use brushLinkPort_.isChanged() above?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +     * @param source   must be provided if action is equal to BrushingAction::Filter
Don't have a strong opinion either way here, but always requiring the source would make the interface more consistent, and even if the source is not required, it might be useful for debugging logging, the manager could for example show the source of the current selection.

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    bool modifiedSelection() const;
can you see which target that is changed?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    //! convenience function for action(BrushingAction::Filter, target, idx)
```suggestion
    //! convenience function for brush(BrushingAction::Filter, target, idx)
```

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    //! convenience function for action(BrushingAction::Select, target, idx)
```suggestion
    //! convenience function for brush(BrushingAction::Select, target, idx)
```

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    //! convenience function for action(BrushingAction::Highlight, target, idx)
```suggestion
    //! convenience function for brush(BrushingAction::Highlight, target, idx)
```

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +                BrushingTarget target = BrushingTarget::Row);
```suggestion
    void filter(const BitSet& idx, BrushingTarget target, std::string_view src);
```
To be consistent with brush

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    //! convenience function for action(BrushingAction::Filter, target, idx)
I would put these together with brush

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    size_t getNumberOfFiltered(BrushingTarget target = BrushingTarget::Row) const;
might add `size_t getNumber(BrushingAction action, BrushingTarget target = BrushingTarget::Row) const;`

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    //! convenience function for action(BrushingAction::Filter, target, idx)
same goes for the other convenience functions

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/brushingaction.h
> +    std::string_view findOrAdd(std::string_view target) {
I would move this to the cpp with all the headers that are needed for this...

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/brushingaction.h
> +}
Move this inline to the friend declaration, to make it a "hidden friend"

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/datastructures/indexlist.h
>  #include <unordered_set>
unordered_set is not needed?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    using type = void;
might also change that error message to remove the need for this?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    bool isModified() const;
overload isChanged?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/processors/brushingandlinkingprocessor.h
> -    ButtonProperty clearFilter_;
Might be nice to be able to do this somehow. question is how to communicate that to the filter sources... outside fo this PR though...

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
I think the union/intersect/latest semantics is encoded in the action type. i.e. selection and highlight is always lates, filter is always union. if you want a different semantics, we should add a new action type.

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    return bool(modifiedActions_ & BrushingModification::Filtered);
```suggestion
    return modifiedActions_.contains(BrushingModification::Filtered);
```
I think that is much easier to read

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    static BitSet empty;
```suggestion
    static const BitSet empty;
```

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    if (std::holds_alternative<BitSetTargets>(selections_[actionIdx])) {
why not use visit here? (just to be consistent?)

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +               selections_[actionIdx]);
```suggestion
    std::visit([&](auto& map) {
        const auto it = map.find(target);
        if (it != map.end()) {
            it->second.clear();
        },
        selections_[actionIdx]);
```

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    return std::visit(util::overloaded{[&](const BitSetTargets& map) {
could use one lambda with auto here to

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +            util::overloaded{
could just use one lambda with auto...

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    return std::visit(util::overloaded{[&](const BitSetTargets& map) {
could just use one lambda with auto...

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    std::unordered_set<BrushingAndLinkingManager*> children_;
why a set?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +                                  BrushingModification::Highlighted);
```suggestion
        modifiedActions_ = BrushingModifications(flags::any);
```
If my memory serves me right

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +            std::visit(util::overloaded{[](BrushingAndLinkingInport* p) { return p->getPath(); },
use auto for the parameter

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +                       selections_[actionIdx]);
this is used in a few places, might make it a private member... getBitset(action, taget)?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    if (std::holds_alternative<BrushingAndLinkingOutport*>(owner_)) {
could all of this not be managed in the removeChild method? why not?

2021-10-19 10:42 UTC, petersteneteg commented on modules/brushingandlinking/src/ports/brushingandlinkingports.cpp
> +    manager_.serialize(s);
why not d.serialize("manager", manager); ?

2021-10-19 11:45 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    bool modifiedSelection() const;
Would be quite useful when trying to prevent loops in the brushing

2021-10-19 11:49 UTC, martinfalk commented on CHANGELOG.md
> +**Update Note:** In case you are using `port.isChanged()` on a `BrushingAndLinkingInport`, you **must** replace this with one of the calls above. Otherwise your selection might no longer be updated.
I did not want to overload onChange() originally. But it would be an option, yes.

2021-10-19 11:50 UTC, martinfalk commented on modules/basegl/include/modules/basegl/processors/sphererenderer.h
> -                                 [&](uint32_t i) { return selection.count(indexBuffer[i]) > 0; });
overlooked that one.

2021-10-19 11:54 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/brushingandlinkingmanager.h
> +    bool modifiedSelection() const;
That would then be a list of targets if we want that.

2021-10-19 12:10 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
> I think the union/intersect/latest semantics is encoded in the action type. i.e. selection and highlight is always lates, filter is always union. if you want a different semantics, we should add a new action type.

I disagree that it is encoded in the action type, but the ones we have now is probably the most commonly used and covers many use cases

2021-10-19 12:23 UTC, petersteneteg commented on CHANGELOG.md
> +**Update Note:** In case you are using `port.isChanged()` on a `BrushingAndLinkingInport`, you **must** replace this with one of the calls above. Otherwise your selection might no longer be updated.
having both might be confusing...

2021-10-19 12:34 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    using type = void;
connected to the check for type traits of a port

https://github.com/inviwo/inviwo/blob/be406b657492879ea60a3f2fc8adb610b08b738d/include/inviwo/core/common/inviwomodule.h#L408-L416

2021-10-19 14:40 UTC, martinfalk commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +                       selections_[actionIdx]);
note the distinction here with using `nullptr` while in the other case an empty BitSet is used.

2021-10-19 14:56 UTC, martinfalk commented on modules/brushingandlinking/src/ports/brushingandlinkingports.cpp
> +    manager_.serialize(s);
because without that it was not a virtual class. Will change to inherit from Serializable.

2021-10-19 17:24 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](auto& map) {
nit: no need for util::overloaded if there is only one lambda

2021-10-19 17:31 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
What I mean is that we can just define that to be the case, if you need selection with an intersect semantics, just create a new action for that with a new name IntersectionSelection or something.

2021-10-19 17:32 UTC, petersteneteg submitted a review, later dismissed

2021-10-19 17:33 UTC, petersteneteg commented on modules/brushingandlinking/src/ports/brushingandlinkingports.cpp
> +    manager_.serialize(s);
Ahh.. I see. Im fine with either, Its just we usually do it that way...

2021-10-19 17:33 UTC, petersteneteg commented
This is looking really nice I think!

2021-10-19 18:57 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
You don’t want/need to change the plots to support that behavior so I think that the logic belongs to the manager

2021-10-20 08:49 UTC, petersteneteg approved these changes

2021-10-20 11:02 UTC, ResearchDaniel approved these changes
Great work!

2021-10-20 11:02 UTC, ResearchDaniel commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    BitSet filterCache_;
Still should be private?

2021-10-20 11:13 UTC, petersteneteg commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
Ahh I think I understand how you mean, you want that semantic to be configurable by the user at runtime for a specific network / b&l setup? Like for these two plots that are linked to a manager I want a to use use an intersection selection, but for this other one I want a global one.

2021-10-20 11:17 UTC, petersteneteg commented
@ResearchDaniel that has to be an old version see https://github.com/inviwo/inviwo/blob/feature/brushing-highlight/modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h

2021-10-20 12:26 UTC, ResearchDaniel commented
Ah, it seems so!

2021-10-20 12:30 UTC, ResearchDaniel commented on modules/brushingandlinking/src/brushingandlinkingmanager.cpp
> +    std::visit(util::overloaded{[&](BitSetTargets& map) { map[target] = indices; },
Exactly

2021-10-20 18:16 UTC, martinfalk commented on modules/brushingandlinking/include/modules/brushingandlinking/ports/brushingandlinkingports.h
> +    BitSet filterCache_;
the managers are private members in both ports.

2021-10-20 18:16 UTC, merged