Fix/meshrendering discard transparent frags
inviwo/inviwo pull request #1214
Opened 2021-10-15 09:45 UTC by eriksunden

Minor fix to MeshRendering processor, such that it discard completely transparent fragements from being rendered.

2021-10-17 19:04 UTC, ResearchDaniel approved these changes

2021-10-17 19:04 UTC, ResearchDaniel commented
@martinfalk Any objections?

2021-10-18 07:23 UTC, petersteneteg requested changes
pls, rebase this on master and force push it, We never merge master into a feature branch. 
Would also be nice with a comment about the reasoning.

2021-10-18 08:18 UTC, ResearchDaniel commented
See #1215

2021-10-18 08:18 UTC, closed without merging