Core/Various: Cleanup of includes to reduce overall compile time
inviwo/inviwo pull request #1341
Opened 2022-09-15 07:39 UTC by petersteneteg

We have tried to cleanup and remove and break some include dependencies in inviwo core to reduce the overall compile time
We have generally tried to reduce the use of big includes that has a many transitive includes. And tried to break up some headers into smaller parts to avoid having to include unused things.
For example the `inviwo/core/util/glm.h` header had been broken up into several smaller headers, `glmvec.h`, `glmmat.h`, `glmcomp.h`, `glmconver.h`, and`glmutils.h`.
Several new utility headers has also been extended or added. For example `inviwo/core/common/inviwoapplicationutil.h` can now be used to get an `InviwoApplication` pointer without the need of including all of inviwoapplication.h
similarly there is a `inviwo/core/common/factoryutil.h` to easily get to various factories, and a `inviwo/core/util/moduleutils.h` to get to various inviwo modules.

These changes seems to have drop the single core wall time from almost 7 hours to closer to 5 hours on my setup. But there is a lot of noise in the measurements...

2022-09-19 11:15 UTC, martinfalk requested changes
Nice work. Some minor comments.

2022-09-19 11:15 UTC, martinfalk commented on CHANGELOG.md
> +similarly there is a `inviwo/core/common/factoryutil.h` to easily get to various factories, and a `inviwo/core/util/moduleutils.h` to get to various inviwo modules.
```suggestion
We cleaned up, removed, and broke some include dependencies in inviwo core to reduce the overall compile time.
We have generally tried to reduce the use of big includes that have many transitive includes. Additionally, we tried to break up some headers into smaller parts to avoid having to include unused things.
For example the `inviwo/core/util/glm.h` header has been broken up into several smaller headers: `glmvec.h`, `glmmat.h`, `glmcomp.h`, `glmconver.h`, and`glmutils.h`.
Several new utility headers have also been added or extended. For example, `inviwo/core/common/inviwoapplicationutil.h` can now be used to get an `InviwoApplication` pointer without the need of including all of `inviwoapplication.h`.
Similarly there is a `inviwo/core/common/factoryutil.h` to easily access various factories, and a `inviwo/core/util/moduleutils.h` to get to various inviwo modules.
```

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/common/factoryutil.h
> + * @see RepresentationConverterMetaFactory
`@see` can contain multiple references on the same line [doxygen docs](https://www.doxygen.nl/manual/commands.html#cmdsa)

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/common/factoryutil.h
> +IVW_CORE_API CameraFactory* getCameraFactory(Property* property);
should each of these be grouped as well?

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/common/factoryutil.h
> +}  // namespace inviwo
missing newline

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/datastructures/coordinatetransformer.h
> + *      │      I │                                 │      V │
```suggestion
 *  │               ModelM.               WorldM.               │                         
 *  │   ┌────────┐──────────▶┌────────┐──────────▶┌────────┐   │                         
 *  │   │        │           │        │            │        │   │                         
 *  │   │  Data  │           │ Model  │            │ World  │   │                         
 *  │   │        │ ModelM.-1 │        │  WorldM.-1 │        │   │                         
 *  │   └────────┘◀──────────└────────┘◀──────────└────────┘   │                         
 *  │   │        ▲                                 │        ▲   │                         
 *  └───┼────────┼─────────────────────────────────┼─────   ┼───┘                         
 *      │      I │                                 │      V │                             
```

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/properties/optionproperty.h
> +        return OrdinalPropertyTraits<T>::classIdentifier();
see comment optionpropertytraits.h

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/properties/optionpropertytraits.h
> +struct OrdinalPropertyTraits {
```suggestion
struct OptionPropertyTraits {
```

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/util/fileextension.h
> +struct OrdinalPropertyTraits<FileExtension> {
see comment optionpropertytraits.h

2022-09-19 11:15 UTC, martinfalk commented on include/inviwo/core/util/formats.h
> +/*
remove commented block

2022-09-19 11:15 UTC, martinfalk commented on modules/base/src/algorithm/meshutils.cpp
> +        {std::atan(std::sqrt(2.0f) / 5.0f), glm::quarter_pi<float>()},
```suggestion
        {std::atan(glm::root_two<float>() / 5.0f), glm::quarter_pi<float>()},
```

glm has functions for sqrt of 2, 3, and 5.

2022-09-19 11:15 UTC, martinfalk commented on modules/base/src/algorithm/meshutils.cpp
> +        {std::atan((2.0f * std::sqrt(2.0f)) / 3.0f), glm::quarter_pi<float>()},
```suggestion
        {std::atan((2.0f * glm::root_two<float>()) / 3.0f), glm::quarter_pi<float>()},
```

2022-09-19 11:15 UTC, martinfalk commented on modules/base/src/algorithm/meshutils.cpp
>          {std::atan(std::sqrt(5.0f) / 4.0f), std::atan(2.0f)},
```suggestion
        {std::atan(glm::root_five<float>() / 4.0f), std::atan(2.0f)},
```

2022-09-19 11:15 UTC, martinfalk commented on modules/opengl/include/modules/opengl/shader/shader.h
>  }  // namespace inviwo
missing newline

2022-09-19 12:52 UTC, petersteneteg commented on include/inviwo/core/datastructures/coordinatetransformer.h
> + *      │      I │                                 │      V │
?

2022-09-19 12:52 UTC, petersteneteg commented on include/inviwo/core/properties/optionpropertytraits.h
> +struct OrdinalPropertyTraits {
haha nice catch...

2022-09-19 12:56 UTC, petersteneteg commented on modules/base/src/algorithm/meshutils.cpp
> +        {std::atan(std::sqrt(2.0f) / 5.0f), glm::quarter_pi<float>()},
I think that just make it harder to read, for minute gains...

2022-09-20 11:44 UTC, martinfalk commented on include/inviwo/core/datastructures/coordinatetransformer.h
> + *      │      I │                                 │      V │
Fixes the right-most line.

2022-09-20 11:45 UTC, martinfalk approved these changes

2022-09-21 15:39 UTC, merged