Feature/iwyu part 4
inviwo/inviwo pull request #1352
Opened 2022-09-30 19:42 UTC by petersteneteg

Changes proposed in this PR:
 * Include cleanup for a number of modules

This should be the last of the core modules

2022-10-04 14:01 UTC, martinfalk approved these changes, later dismissed

2022-10-07 08:42 UTC, martinfalk commented
Include removal of `QMenu` was a bit too aggressive.
```
Error: D:\a\inviwo\inviwo\inviwo\modules\qtwidgets\include\modules/qtwidgets/properties/anglepropertywidgetqt.h(117,33): error C2027: use of undefined type 'QMenu' [D:\a\inviwo\inviwo\build\modules\qtwidgets\inviwo-module-qtwidgets.vcxproj]
```

```
Warning: /home/runner/work/inviwo/inviwo/inviwo/modules/qtwidgets/include/modules/qtwidgets/properties/ordinalminmaxpropertywidgetqt.h:291:31: warning: invalid use of incomplete type ‘class QMenu’
  291 |     auto settingsAction = menu->addAction(tr("&Property settings..."));
      |                               ^~
In file included from /home/runner/work/inviwo/inviwo/inviwo/modules/qtwidgets/include/modules/qtwidgets/properties/ordinalminmaxpropertywidgetqt.h:37,
                 from /home/runner/work/inviwo/inviwo/inviwo/modules/qtwidgets/src/properties/ordinalminmaxpropertywidgetqt.cpp:30:
/home/runner/work/inviwo/inviwo/inviwo/modules/qtwidgets/include/modules/qtwidgets/inviwoqtutils.h:66:7: note: forward declaration of ‘class QMenu’
   66 | class QMenu;
      |       ^~~~~
```

2022-10-10 17:24 UTC, ResearchDaniel requested changes
Is it intentional that warn/push/pop is removed in many places?

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/animationviewqt.cpp
> +
Add back
include <warn/push>
 #include <warn/ignore/all>

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/demo/demonavigatordockwidgetqt.cpp
> +
Warn push/pop

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/sequenceeditor/controlsequenceeditor.cpp
> +
Warn push/pop

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/sequenceeditor/keyframeeditorwidget.cpp
> +#include <QComboBox>       // for QComboBox
Warn push/pop

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/sequenceeditor/propertysequenceeditor.cpp
> +#include <QComboBox>       // for QComboBox
Warn push/pop

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/sequenceeditor/sequenceeditorwidget.cpp
> +#include <QVBoxLayout>  // for QVBoxLayout
Warn push/pop?

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/trackcontrolswidgetqt.cpp
> +#include <QAction>       // for QAction
Warn push/pop?

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/widgets/editorconstants.cpp
> +#include <QApplication>  // for QApplication
Warn push/pop

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/widgets/keyframesequencewidgetqt.cpp
> +#include <QApplication>     // for QApplication
Warn push/pop

2022-10-10 17:24 UTC, ResearchDaniel commented on modules/animationqt/src/animationeditordockwidgetqt.cpp
> -#include <warn/pop>
Warn pop removed, but not push

2022-10-10 18:54 UTC, petersteneteg commented
yes, the warn pop/push are removed intentionally. It seems most most warnings they were needed for has been fixed upstream

2022-10-10 18:57 UTC, petersteneteg commented on modules/animationqt/src/animationeditordockwidgetqt.cpp
> -#include <warn/pop>
good catch

2022-10-10 18:58 UTC, ResearchDaniel commented
> yes, the warn pop/push are removed intentionally. It seems most most warnings they were needed for has been fixed upstream

Ok. I saw at least one place where the pop was removed, but not the push

2022-10-10 19:37 UTC, ResearchDaniel approved these changes

2022-10-10 19:37 UTC, ResearchDaniel commented on tools/iwyu/README.md
> +Fixes for qt, modify iwyu to avoid some circular include in global.h see
```suggestion
Fixes for qt. Modify IWYU (Include What You Use) to avoid some circular include in global.h, see
```

2022-10-11 06:48 UTC, merged

2022-10-11 17:57 UTC, ResearchDaniel commented
@petersteneteg The following includes are incompatible with Qt5:
#include <QEventPoint>      // for QEventPoint, QEventPoi...
#include <QInputDevice>     // for QInputDevice, QInputDe...
#include <QPointingDevice>  // for QPointingDevice
#include <QIODeviceBase>    // for QIODeviceBase::WriteOnly

2022-10-11 18:36 UTC, petersteneteg commented
Ahh... I forgot about qt5 when doing this. Are you building with qt5 still? I just updated to 6.4, is there any good reason to keep qt5 support?

2022-10-11 19:08 UTC, ResearchDaniel commented
Using it on one of my computers still. No special reason except for backwardscompatibility I think.

2022-10-12 07:04 UTC, petersteneteg commented
Do you think we should keep supporting it?

2022-10-12 11:02 UTC, ResearchDaniel commented
How about bumping version and loosing support?