Linking
inviwo/inviwo pull request #140
Opened 2018-05-30 15:03 UTC by petersteneteg

Editor/Core: Some cleanup of the link dialog. added a canLink and canConnect to the ProcessorNetwork. Added a propertyconverter for optionproperty to string

2018-05-30 19:15 UTC, ResearchDaniel requested changes
Some changes and comments

2018-05-30 19:15 UTC, ResearchDaniel commented on src/qt/editor/inviwomainwindow.cpp
>      , undoManager_(this) {
Typo: to the latest

2018-05-30 19:15 UTC, ResearchDaniel commented on include/inviwo/core/properties/propertyconverter.h
> +        convertimpl(static_cast<const SrcProperty *>(src), static_cast<DstProperty *>(dst));
Static Cast ok here?

2018-05-30 19:15 UTC, ResearchDaniel commented on include/inviwo/core/properties/propertyconverter.h
>      virtual void convert(const Property *src, Property *dst) const override {
Throw if no conversion can be made?

2018-05-31 07:04 UTC, petersteneteg commented on include/inviwo/core/properties/propertyconverter.h
> +        convertimpl(static_cast<const SrcProperty *>(src), static_cast<DstProperty *>(dst));
Yes, since we use the CLASS_IDENTIFIERs to make sure we only use a converter for the right pair of properties

2018-05-31 07:05 UTC, petersteneteg commented on include/inviwo/core/properties/propertyconverter.h
>      virtual void convert(const Property *src, Property *dst) const override {
we only use the converter for the property types it is registered for....

2018-05-31 07:08 UTC, petersteneteg commented on include/inviwo/core/properties/propertyconverter.h
>      virtual void convert(const Property *src, Property *dst) const override {
added some comment about this...

2018-05-31 07:24 UTC, ResearchDaniel approved these changes

2018-05-31 09:08 UTC, merged