Feature/std filesystem
inviwo/inviwo pull request #1403
Opened 2023-04-06 11:35 UTC by petersteneteg

Changes proposed in this PR:
 * Adopt std::filesystem for any file related things
This has been tested on: Mac/Win

2023-04-12 10:03 UTC, martinfalk requested changes
Nice. Switch to std::filesystem should be mentioned in changelog.

2023-04-12 10:03 UTC, martinfalk commented on modules/python3/bindings/src/pyimage.cpp
> +                                     filepath);
```suggestion
                     throw Exception(IVW_CONTEXT_CUSTOM("exposeImage"), "No writer for {}",
                                     filepath);
```

2023-04-12 10:03 UTC, martinfalk commented on src/core/tests/unittests/filesystem-test.cpp
> +/*
Why exclude those tests? 
Unit tests should probably be removed if no longer necessary due to `std::filesystem`.

2023-04-12 10:03 UTC, martinfalk commented on src/core/util/filesystem.cpp
> +std::fstream fstream(const fs::path& filename, std::ios_base::openmode mode) {
This looks like `inviwo::filesystem::fstream / ifstream / ostream` are no longer necessary?

2023-04-12 10:03 UTC, martinfalk commented on src/core/util/filesystem.cpp
> +fs::path getWorkingDirectory() {
WIN32 path uses deprecated `cleanupPath(util::fromWstring(buff));`

2023-04-12 10:03 UTC, martinfalk commented on src/core/util/filesystem.cpp
> +    chdir(path.c_str());
use return value of `chdir`

2023-04-12 10:03 UTC, martinfalk commented on src/core/util/filesystem.cpp
> +fs::path getInviwoBinDir() {
WIN32: `getFileDirectory()` is deprecated

2023-05-08 14:20 UTC, martinfalk requested changes
Looking good, minor comments.

2023-05-08 14:20 UTC, martinfalk commented on CHANGELOG.md
> +
```suggestion
## 2023-05-05 `std::filesystem` adoption
Inviwo has been updated to use `std::filesystem` instead of our own custom functions.
This change is not backwards compatible and will require code changes. 
The change is motivated by the fact that `std::filesystem` is now part of the C++ standard since C++17
and is supported by all major compilers. This also makes it easier to use the same code
in Inviwo and other projects that use `std::filesystem`, and removes the burden of maintaining 
a lot of platform specific code.

### Migration guide
All path-related functions that used to take a `const std::string&` or
`std::string_view` argument now use `const std::filesystem::path&`. For the most part simply 
switching the argument type in all places where it fails to compile will be sufficient.
But it might be good to review the code to avoid any unnecessary conversions between `std::string` 
and `std::filesystem::path` since the conversion is implicit and can be hard to spot.
It should also be noted that the type of the implicit conversion is platform dependent, on Windows 
a `std::filesystem::path` will be converted to a `std::wstring` while on Linux and Mac it will be
converted to a `std::string`.

Many of the functions in `inviwo/core/util/filesystem.h` have been deprecated since they are now 
replaced by the ones in std::filesystem.

The fmt lib also supports formatting `std::filesystem::path`s by including the `fmt/std.h` header.
While formatting a path, fmt will automatically surround the path with quotes. If you have code that 
does something like `fmt::format("{}/{}", path, file)` to generate a file path, you will have to change it to `path / file` without using fmt instead.
Since the extra quotes inserted while formatting will make the path ill formed. 

```

2023-05-08 14:20 UTC, martinfalk commented on include/inviwo/qt/editor/inviwomainwindow.h
> +    ///< Use delayed initialization as it can be expensive.
Use `///` or `//!`. Using `///<` refers to the left of the comment.
```suggestion
    /// Use delayed initialization as it can be expensive.
```

2023-05-08 14:20 UTC, martinfalk commented on src/qt/editor/inviwomainwindow.cpp
> +                    LogInfo("Exported network to \"" << path << "\"");
```suggestion
                    LogInfo("Exported network to " << path);
```

2023-05-08 17:25 UTC, martinfalk approved these changes, later dismissed

2023-05-08 19:14 UTC, ResearchDaniel requested changes
Great work!
Some minor suggestions for improvements.

Also, I think that this change deserves a version 1.0 :)

2023-05-08 19:14 UTC, ResearchDaniel commented on .github/workflows/inviwo.yml
> +        os: [windows-latest, macos-13, ubuntu-22.04]
Should add a comment about the macos-13 requirement

2023-05-08 19:14 UTC, ResearchDaniel commented on .github/workflows/inviwo.yml
> +        sudo xcode-select --switch /Applications/Xcode_14.3.app/Contents/Developer
Could add a comment about the 14.3 requirement to aid in future updates

2023-05-08 19:14 UTC, ResearchDaniel commented on apps/minimals/glfw/glfwminimum.cpp
> +    inviwo::util::configureCodePage();
Perhaps we can comment about what this does as the minimums are meant to be examples.

2023-05-08 19:14 UTC, ResearchDaniel commented on ext/CMakeLists.txt
> -# tinydir
Nice!

2023-05-08 19:14 UTC, ResearchDaniel commented on include/inviwo/core/util/localetools.h
> +void IVW_CORE_API configureCodePage();
Missing documentation

2023-05-08 19:14 UTC, ResearchDaniel commented on include/inviwo/core/util/filesystem.h
> +[[deprecated]] IVW_CORE_API std::filesystem::path cleanupPath(std::string_view path);
Is this replaced by stripIdentifier? ```suggestion
[[deprecated]] IVW_CORE_API std::filesystem::path cleanupPath(std::string_view path);
```
```suggestion
[[deprecated("Use util::stripIdentifier() instead.")]] IVW_CORE_API std::filesystem::path cleanupPath(std::string_view path);
```

2023-05-08 19:14 UTC, ResearchDaniel commented on include/inviwo/core/util/filesystem.h
> +[[deprecated]] IVW_CORE_API std::string getFileExtension(const std::filesystem::path& url);
```suggestion
[[deprecated("Use std::filesystem::path::extension instead, but note that the function includes the dot")]] IVW_CORE_API std::string getFileExtension(const std::filesystem::path& url);
```

2023-05-08 19:14 UTC, ResearchDaniel commented on include/inviwo/core/util/filesystem.h
> +[[deprecated]] IVW_CORE_API bool fileExists(const std::filesystem::path& filePath);
```suggestion
[[deprecated"Use std::filesystem::is_regular_file" instead")]] IVW_CORE_API bool fileExists(const std::filesystem::path& filePath);
```

2023-05-09 06:31 UTC, martinfalk approved these changes

2023-05-09 09:27 UTC, ResearchDaniel approved these changes

2023-05-09 11:22 UTC, merged

2023-05-09 11:23 UTC, petersteneteg commented
Want to remove the submodules and fix the python installation stuff before 1.0