Feature/network size
inviwo/inviwo pull request #1411
Opened 2023-05-02 11:05 UTC by petersteneteg

Fixes #...

Changes proposed in this PR:
 * ...
 * ...
 * ...

This has been tested on: ...

> Thank you for contributing to the Inviwo repository! Please ensure the following: 
> - Code is error and warning free
> - Code follows the Inviwo coding guidelines: 
>   https://github.com/inviwo/inviwo/wiki/Coding-Conventions
> - New Code / Processors follows the Inviwo documentation guidelines: 
>   https://github.com/inviwo/inviwo/wiki/Documentation-guide
> - New Code / processors are tested in a unittest and / or regression test: 
>   https://github.com/inviwo/inviwo/wiki/Manual#testing
> 
> Please remember to specify the environment this code been compiled and tested on:
> Operating System / Compiler / IDE / QT / CMake / Python versions.

2023-05-02 13:52 UTC, martinfalk requested changes

2023-05-02 13:52 UTC, martinfalk commented on include/inviwo/core/network/processornetwork.h
> +     * @return is the network empty i.e. does it have any processors
```suggestion
     * @return whether the network is empty, that is the network contains no processors
```

2023-05-02 13:52 UTC, martinfalk commented on include/inviwo/core/network/processornetwork.h
> +     * @return the number of processors in the network;
```suggestion
     * @return the number of processors in the network
```

2023-05-03 05:57 UTC, ResearchDaniel approved these changes

2023-05-03 06:29 UTC, martinfalk approved these changes

2023-05-03 06:33 UTC, martinfalk approved these changes

2023-05-03 15:59 UTC, merged