Feature/fileprop features
inviwo/inviwo pull request #1420
Opened 2023-05-09 13:53 UTC by petersteneteg

Fixes #...

Changes proposed in this PR:

2023-05-09 18:06 UTC, ResearchDaniel submitted a review, later dismissed
Nice!
Will approve if it can be confirmed that there is no need for updating old workspaces

2023-05-09 18:06 UTC, ResearchDaniel commented on include/inviwo/qt/editor/workspaceannotationsqt.h
> +    static std::map<std::string, int> workspaceProcessorsCounts(
```suggestion
    static std::map<std::string, int> workspaceProcessorsCount(
```

2023-05-09 18:06 UTC, ResearchDaniel commented on modules/qtwidgets/include/modules/qtwidgets/editorsettings.h
> +class IVW_MODULE_QTWIDGETS_API EditorSettings : public Settings {
Should this setting belong to the QtWidgets module?

is it not better to put it in the editor?

2023-05-09 18:06 UTC, ResearchDaniel commented on modules/qtwidgets/src/filepathlineeditqt.cpp
> +    warningLabel_->setToolTip("Could not locate file!");
```suggestion
    warningLabel_->setToolTip("Could not locate file");
```

2023-05-09 18:06 UTC, ResearchDaniel commented on src/core/properties/fileproperty.cpp
>      // Explicitly set the file name here since the TemplateProperty itself is initialized with an
Is this still needed?

2023-05-09 18:06 UTC, ResearchDaniel commented on src/core/properties/fileproperty.cpp
> +        modified |= update(fileMode_, static_cast<FileMode>(fileMode));
Is there a need for updating the workspace? What happens if it was previously set to DirectoryOnly?

2023-05-09 18:06 UTC, ResearchDaniel commented on src/qt/editor/workspacegridview.cpp
> +    QTreeView* view_;
Would call this parent_

2023-05-09 18:45 UTC, petersteneteg commented on include/inviwo/qt/editor/workspaceannotationsqt.h
> +    static std::map<std::string, int> workspaceProcessorsCounts(
there is one count, per processor type...

2023-05-09 18:46 UTC, petersteneteg commented on modules/qtwidgets/include/modules/qtwidgets/editorsettings.h
> +class IVW_MODULE_QTWIDGETS_API EditorSettings : public Settings {
Well the editor is not a module... some of it was in the core system settings before... think this is better at least.

2023-05-09 18:47 UTC, petersteneteg commented on src/core/properties/fileproperty.cpp
>      // Explicitly set the file name here since the TemplateProperty itself is initialized with an
That is not affected by this change.

2023-05-09 18:52 UTC, petersteneteg commented on src/qt/editor/workspacegridview.cpp
> +    QTreeView* view_;
not really, need the fact that it is the view to figure out the total size to be able to do text eliding..

2023-05-09 19:11 UTC, petersteneteg commented on src/core/properties/fileproperty.cpp
> +        modified |= update(fileMode_, static_cast<FileMode>(fileMode));
you would probably end up with AnyFile since that is the default... so you might be able to enter regular files not just directories... will see If I can add a converter easily...

2023-05-11 09:40 UTC, petersteneteg commented on src/core/properties/fileproperty.cpp
> +        modified |= update(fileMode_, static_cast<FileMode>(fileMode));
added a converter

2023-05-11 12:01 UTC, martinfalk requested changes
Nice features.

2023-05-11 12:01 UTC, martinfalk commented on modules/qtwidgets/src/editorsettings.cpp
> +          "The maximum number of backup files to store, the oldest will be removed frist"_help, 24,
```suggestion
          "The maximum number of backup files to keep, the oldest will be removed first"_help, 24,
```

2023-05-11 12:01 UTC, martinfalk commented on modules/qtwidgets/src/inviwofiledialog.cpp
> +inviwo::AcceptMode InviwoFileDialog::getAcceptMode() const {
```suggestion
AcceptMode InviwoFileDialog::getAcceptMode() const {
```

2023-05-11 12:01 UTC, martinfalk commented on resources/stylesheets/inviwo.qss
> +    background: #3a3a3d;
`background: transparent;` should be removed

Did you check this doesn't break anything?

2023-05-11 12:01 UTC, martinfalk commented on src/qt/editor/inviwomainwindow.cpp
> +                        if (!recentFiles[i].isEmpty()) {
Could this happen? If so, doesn't this mess with the numbering?

2023-05-11 12:01 UTC, martinfalk commented on src/qt/editor/undomanager.cpp
> +                    int restoreFrequency = 1440;
every 24 minutes?

2023-05-11 12:07 UTC, petersteneteg commented on resources/stylesheets/inviwo.qss
> +    background: #3a3a3d;
```suggestion
```

2023-05-11 12:11 UTC, petersteneteg commented on src/qt/editor/inviwomainwindow.cpp
> +                        if (!recentFiles[i].isEmpty()) {
that was there before... did not change that part

2023-05-11 12:13 UTC, petersteneteg commented on src/qt/editor/undomanager.cpp
> +                    int restoreFrequency = 1440;
not sure how I selected that one... will be overwritten by the default in the editor settings though...

2023-05-11 13:01 UTC, martinfalk approved these changes

2023-05-12 07:19 UTC, merged