Sampler refactoring
inviwo/inviwo pull request #1504
Opened 2024-03-01 11:24 UTC by petersteneteg

Core/Base/VecVis: Sampler refactoring. Use a single type for the sample return value

Fixes #...

Changes proposed in this PR:
 * ...
 * ...
 * ...

This has been tested on: ...

> Thank you for contributing to the Inviwo repository! Please ensure the following: 
> - Code is error and warning free
> - Code follows the Inviwo coding guidelines: 
>   https://github.com/inviwo/inviwo/wiki/Coding-Conventions
> - New Code / Processors follows the Inviwo documentation guidelines: 
>   https://github.com/inviwo/inviwo/wiki/Documentation-guide
> - New Code / processors are tested in a unittest and / or regression test: 
>   https://github.com/inviwo/inviwo/wiki/Manual#testing
> 
> Please remember to specify the environment this code been compiled and tested on:
> Operating System / Compiler / IDE / QT / CMake / Python versions.

2024-03-01 11:52 UTC, martinfalk approved these changes
Nice work!

2024-03-01 11:52 UTC, martinfalk commented on modules/base/src/processors/volumesequencesingletimestepsampler.cpp
```suggestion
    R"(Creates a spatial sampler for a given timestamp from a VolumeSequence. Will use linear
    interpolation to sample between two adjacent volumes in the sequence.
    Useful for streamline visualization of a specific time step.)"_unindentHelp};
```

2024-03-01 11:52 UTC, martinfalk commented on modules/base/src/processors/volumesequencesingletimestepsampler.cpp
> +    , timestamp_("timestamp", "Timestamp", "the timestamp to sample at"_help) {
```suggestion
    , timestamp_("timestamp", "Timestamp", "The timestamp to sample at"_help) {
```

2024-03-01 12:58 UTC, martinfalk submitted a review, later dismissed

2024-03-05 10:40 UTC, ResearchDaniel requested changes

2024-03-05 10:40 UTC, ResearchDaniel commented on include/inviwo/core/util/imagesampler.h
> +     * Creates a ImageSampler for the given LayerRAM, does not take ownership of ram.
```suggestion
     * Creates an ImageSampler for the given LayerRAM. Does not take ownership of supplied data.
```

2024-03-05 10:40 UTC, ResearchDaniel commented on include/inviwo/core/util/imagesampler.h
> +     * Use ImageSampler(std::shared_ptr<const Image>) to ensure that the LayerRAM is
```suggestion
     * @note Use ImageSampler(std::shared_ptr<const Image>) to ensure that the LayerRAM is
```

2024-03-05 10:40 UTC, ResearchDaniel commented on modules/base/include/modules/base/processors/layertospatialsampler.h
> +    DataOutport<SpatialSampler<dvec4>> sampler_;
Wrong?
```suggestion
    DataOutport<SpatialSampler<dvec2>> sampler_;
```

2024-03-05 10:40 UTC, ResearchDaniel commented on modules/base/src/processors/layertospatialsampler.cpp
> +    auto sampler = std::make_shared<ImageSampler<dvec4>>(layer_.getData());
Wrong?
```suggestion
    auto sampler = std::make_shared<ImageSampler<dvec2>>(layer_.getData());
```

2024-03-05 10:40 UTC, ResearchDaniel commented on modules/base/src/processors/volumesequencesingletimestepsampler.cpp
> +        return v0_.withinBounds(pos, CoordinateSpace::Data) ||
```suggestion
        return v0_.withinBounds(pos, CoordinateSpace::Data) &&
```

2024-03-05 10:47 UTC, petersteneteg commented on modules/base/src/processors/layertospatialsampler.cpp
> +    auto sampler = std::make_shared<ImageSampler<dvec4>>(layer_.getData());
Wanted to change it to dvec4 but that has to wait until a future pr.

2024-03-05 11:27 UTC, ResearchDaniel approved these changes

2024-03-05 15:11 UTC, merged