Core,Qt: commandline arg to reset Qt window state
inviwo/inviwo pull request #1521
Opened 2024-04-15 14:54 UTC by martinfalk

Fixes 
* ignores the previously stored window state and geometry of the Inviwo main window on startup. This should fix broken toolbars.

2024-04-15 15:30 UTC, ResearchDaniel approved these changes, later dismissed
Is there a way to automatically detect that it is broken and either do it or advice the user to do it?

2024-04-16 07:18 UTC, martinfalk commented
> Is there a way to automatically detect that it is broken and either do it or advice the user to do it?

Other than looking at a totally cramped toolbar, don't think so. Once Inviwo is running, it would be quite tricky to purge the broken state as all UI elements have a potentially broken state that is synced automatically.

2024-04-16 09:27 UTC, petersteneteg requested changes
Move to inviwomainwindow

2024-04-16 18:10 UTC, petersteneteg approved these changes

2024-04-16 18:13 UTC, petersteneteg commented
> Is there a way to automatically detect that it is broken and either do it or advice the user to do it?

We have no way of knowing that we know of...

2024-04-23 09:18 UTC, merged