Core,OpenGL: two-sided illumination
inviwo/inviwo pull request #1537
Opened 2024-05-13 11:10 UTC by martinfalk

The current shading only considers surfaces facing toward the camera. This leads to unwanted results for thin meshes like stream ribbons or isosurfaces where the "front" side is shaded properly while the backside is only shaded with the ambient term.

Changes proposed in this PR:
* two-sided illumination is now default
* added options for front- and backside only

![image](https://github.com/inviwo/inviwo/assets/9251300/825bac9c-4693-4d7e-ae6e-1b2d3fb63535)

--- 

### Integral lines example: frontside only (left) and two-sided illumination (right)
<img src='https://github.com/inviwo/inviwo/assets/9251300/277c9f2e-60e1-4a5a-bfa4-3494b46bafda' width='250px'><img src='https://github.com/inviwo/inviwo/assets/9251300/7653d0bb-1c24-4dfb-bb0f-3195636b1eee' width='250px'>

2024-05-13 13:38 UTC, petersteneteg submitted a review, later dismissed

2024-05-13 15:03 UTC, ResearchDaniel requested changes, later dismissed
I would argue for incorporating a new enum for front/back/both-sided shading. The manipulation of the normal could be moved outside of the shadeXYZ to also accommodate front/back-face shading for diffuse/specular shading.

2024-05-13 15:03 UTC, ResearchDaniel commented on include/inviwo/core/datastructures/light/lightingstate.h
> +    BlinnPhongFront,
Would it not make more sense to have a separate option with shading of front/back/both sides. This explodes a bit now and it is not entirely clear that for example Phong is both sides (unless one sees the other options)

2024-05-13 15:03 UTC, ResearchDaniel commented on modules/opengl/src/shader/shaderutils.cpp
>                  return "shadeSpecular(lighting, materialSpecularColor, position, normal, "
If you would have the normal manipulation outside of this code snippet you could also have front/back diffuse/specular shading.

2024-05-13 15:03 UTC, ResearchDaniel commented on modules/opengl/glsl/utils/shading.glsl
> +    if (dot(toCameraDir, normal) < 0) {
normal = faceforward(normal, toCameraDir, normal)

2024-05-14 06:33 UTC, petersteneteg commented on include/inviwo/core/datastructures/light/lightingstate.h
> +    BlinnPhongFront,
since it is in the same dropdown in the gui this way it is quite hard to miss. I see not need of a separate option for this.

2024-05-14 06:39 UTC, petersteneteg commented on modules/opengl/src/shader/shaderutils.cpp
>                  return "shadeSpecular(lighting, materialSpecularColor, position, normal, "
if there ever is a demand for selecting two/front/back sided diffuse only shading we could add that then.
No point adding settings that will never be used anyway.

2024-05-14 07:54 UTC, martinfalk commented on modules/opengl/src/shader/shaderutils.cpp
>                  return "shadeSpecular(lighting, materialSpecularColor, position, normal, "
I would rather remove 'diffuse' and 'specular' only (maybe even 'ambient'). Reason: you can always get the same result by setting the other properties to black / zero.

2024-05-16 12:49 UTC, petersteneteg submitted a review, later dismissed

2024-05-17 14:35 UTC, petersteneteg approved these changes, later dismissed

2024-05-21 06:19 UTC, petersteneteg approved these changes

2024-05-22 16:57 UTC, merged