Core: valid identifier fix
inviwo/inviwo pull request #1538
Opened 2024-05-15 12:18 UTC by martinfalk

Fixes
* it was possible to create valid identifiers containing hyphen `-`. But during deserialization hyphens are removed by `util::stripIdentifier` resulting in a broken workspace.

https://github.com/inviwo/inviwo/blob/8432308ab663905635135ef235323d7a41ba2078/src/core/util/utilities.cpp#L190-L197

Changes proposed in this PR:
* hyphen removed from valid identifiers

2024-05-15 13:33 UTC, petersteneteg approved these changes, later dismissed

2024-05-15 14:44 UTC, ResearchDaniel submitted a review, later dismissed

2024-05-21 06:54 UTC, petersteneteg reviewed
Nice work cleaning that up!

2024-05-21 13:37 UTC, martinfalk commented
Running into an issue with `CompositeProcessor` that replaces '.' with '-' in property paths.

https://github.com/inviwo/inviwo/blob/619955590552534c18168adbed1d36802de46fd9/src/core/processors/compositeprocessor.cpp#L303-L304

2024-05-21 19:36 UTC, petersteneteg requested changes

2024-05-21 19:36 UTC, petersteneteg commented on src/core/io/serialization/versionconverter.cpp
> +    xml::visitMatchingNodes(
there can be nested processornetworks, so you have to do a recursive search for ProcessorNetwork/Processors/Processor

2024-05-22 16:46 UTC, petersteneteg approved these changes

2024-05-22 16:47 UTC, merged