Base: LayerRAMSubSet algorithm
inviwo/inviwo pull request #202
Opened 2018-08-07 11:08 UTC by martinfalk

* heavily based on VolumeRAMSubSet

2018-08-08 08:05 UTC, petersteneteg requested changes

2018-08-08 08:05 UTC, petersteneteg commented on modules/base/algorithm/image/layerramsubset.cpp
> +            case DataFormatId::Vec4UInt8: {
Only vec4uint8 dest supported?

2018-08-08 08:05 UTC, petersteneteg commented on modules/base/algorithm/image/layerramsubset.cpp
> +            dstFormat->getId(), disp, in, offset, extent, clampBorderOutsideImage);
DstFormat == null?

2018-08-08 08:05 UTC, petersteneteg commented on modules/base/algorithm/image/layerramsubset.cpp
> +                return dispatching::dispatch<std::shared_ptr<LayerRAM>, dispatching::filter::All>(
Why not dispatch on the layer directly?

2018-08-08 08:05 UTC, petersteneteg commented on modules/base/algorithm/image/layerramsubset.cpp
> +                    dstFormat->getId(), disp, in, offset, extent, clampBorderOutsideImage);
Should the dispatch not be in the source format?

2018-08-08 08:05 UTC, petersteneteg commented on modules/base/algorithm/image/layerramsubset.h
> +            dst[dstPos + i] = util::glm_convert_normalized<Tdst, T>(src[srcPos + i]);
Could do this with a second dispatch...

2018-08-08 09:02 UTC, martinfalk commented on modules/base/algorithm/image/layerramsubset.cpp
> +            case DataFormatId::Vec4UInt8: {
regarding conversion as a target format (as per comment). There was no need to implement a subset + format conversion for other formats besides 8bit rgba.

2018-08-08 09:03 UTC, martinfalk commented on modules/base/algorithm/image/layerramsubset.cpp
> +                return dispatching::dispatch<std::shared_ptr<LayerRAM>, dispatching::filter::All>(
This code is approx. 2 years old and was based on `VolumeRAMSubset`, will fix this.

2018-08-08 09:04 UTC, martinfalk commented on modules/base/algorithm/image/layerramsubset.cpp
> +                    dstFormat->getId(), disp, in, offset, extent, clampBorderOutsideImage);
hm, might work in connection with the second dispatch.

2018-08-22 15:28 UTC, martinfalk commented
Revised PR with respect to requested changes.

2018-08-22 18:35 UTC, petersteneteg approved these changes

2018-08-23 11:07 UTC, merged