Fix/csvexport
inviwo/inviwo pull request #288
Opened 2018-11-08 17:09 UTC by martinfalk

Various fixes and improvements for CSV export.

2018-11-08 18:27 UTC, ResearchDaniel requested changes
Might be some errors. 
Consider renaming FileExtension::all() to FileExtension::any()  (and in that case matchesAny)

2018-11-08 18:27 UTC, ResearchDaniel commented on include/inviwo/core/util/fileextension.h
> +    bool matchesAll() const;
What does this one do? Same as *? Could add a comment

2018-11-08 18:27 UTC, ResearchDaniel commented on include/inviwo/core/util/fileextension.h
>      static FileExtension all();
Not part of this PR but any would probably make more sense :)

2018-11-08 18:27 UTC, ResearchDaniel commented on modules/plotting/processors/dataframeexporter.cpp
> +    if (exportFile_.getSelectedExtension() == xmlExtension_) {
What if the file dialog has not been used, i.e. set via scripting. Should it be:
`exportFile_.getSelectedExtension() == xmlExtension_ || filesystem::getFileExtension(exportFile_) == xmlExtension_`

2018-11-08 18:27 UTC, ResearchDaniel commented on src/core/util/fileextension.cpp
> +    if (extension_.empty()) {
or matchesAll()?

2018-11-08 20:20 UTC, petersteneteg commented on include/inviwo/core/util/fileextension.h
>      static FileExtension all();
the filter is usually called 
>   "*", "All Files"

not "Any Files" hence I think ```all``` makes more sense...

2018-11-09 09:25 UTC, martinfalk commented on include/inviwo/core/util/fileextension.h
> +    bool matchesAll() const;
this one returns true, if the extension only contains an asterisk, i.e. the `FileExtension` matches all files. 
```c++
bool FileExtension::matchesAll() const { return extension_ == "*"; }
```
Will add a comment.

2018-11-09 09:26 UTC, martinfalk commented on include/inviwo/core/util/fileextension.h
>      static FileExtension all();
agree with Peter. I had a look at various file dialogs in different applications.

2018-11-09 09:30 UTC, martinfalk commented on modules/plotting/processors/dataframeexporter.cpp
> +    if (exportFile_.getSelectedExtension() == xmlExtension_) {
Good point. I will move the extension checking from the widget into the fileproperty itself.

2018-11-09 09:31 UTC, martinfalk commented on src/core/util/fileextension.cpp
> +    if (extension_.empty()) {
not necessarily, someone, e.g. @ResearchDaniel, might come along and decide to add a custom `FileExtension("*", "Matches any file")`. Then the description of the FileExtension would not match `::all()`

2018-11-09 13:27 UTC, ResearchDaniel approved these changes

2018-11-14 11:39 UTC, closed without merging