Base: InputSelector: Fix for updatePorts being called multiple times while deserialzing
inviwo/inviwo pull request #380
Opened 2019-01-31 12:33 UTC by r-englund

An inports onConnect function is called several times while deserializing a network. Once per connected outport, first time it is called it only has one connection, second time two connections and so on. This lead to losing which option was selected when serializing and always the first connected port would be used.

2019-01-31 12:56 UTC, petersteneteg approved these changes
Looks like something that we maybe should solve in the deserialization? Would that be possible?

2019-01-31 17:53 UTC, martinfalk requested changes

2019-01-31 17:53 UTC, martinfalk commented on modules/base/include/modules/base/processors/inputselector.h
> +    }
`TemplateOptionProperty::replaceOptions` should be used. It takes care of maintaining the selected item, if it continues to exist.

2019-02-01 08:27 UTC, petersteneteg commented on modules/base/include/modules/base/processors/inputselector.h
>          auto id = port->getProcessor()->getIdentifier();
Should this be identifier or displayname?

2019-02-01 08:41 UTC, martinfalk commented on modules/base/include/modules/base/processors/inputselector.h
>          auto id = port->getProcessor()->getIdentifier();
Suggesting `getDisplayName()` since that one will be more informative. See #381

2019-02-01 11:02 UTC, martinfalk approved these changes

2019-02-01 11:22 UTC, merged