Feature/tiffstack rebase
inviwo/inviwo pull request #413
Opened 2019-02-12 13:59 UTC by martinfalk

2019-02-12 14:22 UTC, ResearchDaniel approved these changes
Nice

2019-02-12 14:22 UTC, ResearchDaniel commented on modules/base/src/processors/imagestackvolumesource.cpp
> +                volume->dataMap_.dataRange =
Future feature: option to automatically decide ranges based on min/max. Especially for other formats, i.e. float

2019-02-12 14:22 UTC, ResearchDaniel commented on modules/cimg/src/cimgutils.cpp
> +    if (extToBaseTypeMap_.find(fileExtension) != extToBaseTypeMap_.end()) {
Remove comments?

2019-02-12 17:53 UTC, martinfalk commented on modules/cimg/src/cimgutils.cpp
> +    if (extToBaseTypeMap_.find(fileExtension) != extToBaseTypeMap_.end()) {
work in progress.

2019-02-12 20:41 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +    std::vector<std::string> fileNames;
Copy_if

2019-02-13 09:04 UTC, petersteneteg requested changes

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +    std::vector<std::string> filesInDirectory = filePattern_.getFileList();
Why warning here but one bellow?

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +    std::vector<std::string> filesInDirectory = filePattern_.getFileList();
Const, ref?

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +    for (auto file : fileNames) {
Const ref

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +        layerDims = imgLayer->getDimensions();
Define here

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +        auto imgLayer = getReaderIt(fileNames[slice])->second->readData(fileNames[slice]);
If skipunsupported is false the iterators might point to nullptrs

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +                volume->dataMap_.dataRange =
This range will works poorly... probably should be a min max calc, or let the user supply min/max

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +                        // reader does not exist for this format
This case is duplicated, needs restructuring

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +                            layer->setDimensions(layerDims);
Is this not destructive?

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +                                if ((DataFormat<ValueType>::numtype != NumericType::Float) &&
This test has to be before all the dispatches, it will never happen inside the dispach, the dispach filter will make sure of that..

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +    if ((layerDims.x == 0) || (layerDims.y == 0) || !format) {
Remove

2019-02-13 09:04 UTC, petersteneteg commented on modules/base/src/processors/imagestackvolumesource.cpp
> +    double aspectRatio = static_cast<double>(layerDims.x) / static_cast<double>(layerDims.y);
Remove use dim*spaceing

2019-02-13 09:07 UTC, martinfalk commented on modules/base/src/processors/imagestackvolumesource.cpp
> +    std::vector<std::string> filesInDirectory = filePattern_.getFileList();
`getFileList()` returns only `std::vector<std::string>`

2019-02-13 10:10 UTC, martinfalk commented on modules/base/src/processors/imagestackvolumesource.cpp
> +                            layer->setDimensions(layerDims);
that is the purpose here. The copy operation assumes identical sizes.

2019-02-13 15:25 UTC, petersteneteg approved these changes

2019-02-14 12:18 UTC, petersteneteg commented
rebased into #417

2019-02-14 12:18 UTC, closed without merging