Feature/tiffstack
inviwo/inviwo pull request #417
Opened 2019-02-14 12:18 UTC by petersteneteg

rebase of #413

2019-02-17 07:55 UTC, ResearchDaniel commented
A bit hard to see if everything works but looks good. Some minor commens

2019-02-18 05:50 UTC, petersteneteg commented
Comments?

2019-02-18 07:50 UTC, ResearchDaniel requested changes

2019-02-18 07:50 UTC, ResearchDaniel commented on modules/base/src/properties/basisproperty.cpp
> +        a_ = that.a_;
Is this not taken care of by CompositeProperty= operator?

2019-02-18 07:50 UTC, ResearchDaniel commented on tests/volumes/boronslice/generate.py
> +
Relative path

2019-02-18 07:50 UTC, ResearchDaniel commented on include/inviwo/core/io/datareaderfactory.h
> +                                                                    const std::string& fallbackExt);
Second arg should be FileExtension type?
Could also mention its use case

2019-02-19 09:40 UTC, petersteneteg commented on modules/base/src/properties/basisproperty.cpp
> +        a_ = that.a_;
Nopes

2019-02-19 09:41 UTC, petersteneteg commented on tests/volumes/boronslice/generate.py
> +
this is run from the python editor, have no idea what a relative path should be.. one has to edit it before use

2019-02-19 09:42 UTC, petersteneteg commented on include/inviwo/core/io/datareaderfactory.h
> +                                                                    const std::string& fallbackExt);
the second arg has to be a string, since we don't have any description for the file extension...

2019-02-19 10:12 UTC, ResearchDaniel approved these changes

2019-02-20 10:45 UTC, merged