Modernized line rendering and added categorical axes
inviwo/inviwo pull request #430
Opened 2019-02-23 16:53 UTC by ResearchDaniel

Dug myself into a rabbit hole... 
- Changed parallel coordinates to use the AxisProperty. 
- Added CategoricalAxisProperty 
- Added picking capabilities for line renderer processor and AxisRenderer
- Unified line renderer with how we use Sphere renderer (vertex shader outputs picking id instead of color)

2019-02-23 19:43 UTC, petersteneteg commented on modules/plotting/include/modules/plotting/utils/axisutils.h
> +std::shared_ptr<Mesh> IVW_MODULE_PLOTTING_API
The _API should come first for a free funktion

2019-02-25 08:17 UTC, ResearchDaniel commented
![image](https://user-images.githubusercontent.com/8738140/53323314-24095f80-38de-11e9-800d-569393e99302.png)

2019-02-25 08:25 UTC, Alboin commented
Looking good! Although it seems to cause some problems in the scatterplot and color scale legend:
![image](https://user-images.githubusercontent.com/8807821/53323745-4e0f5180-38df-11e9-93fb-52f756c76217.png)

2019-02-25 10:13 UTC, ResearchDaniel commented
@Alboin on it

2019-02-27 10:06 UTC, martinfalk commented
Axis labels are no longer pixel aligned. Thus, they appear so blurry.

![image](https://user-images.githubusercontent.com/9251300/53482519-a9784580-3a7f-11e9-8e99-041b24b14371.png)

2019-02-27 16:51 UTC, martinfalk requested changes
Nice. The categorical axes comes in handy for sure.
Some minor changes required.

2019-02-27 16:51 UTC, martinfalk commented on modules/basegl/include/modules/basegl/processors/linerenderer.h
> +	MeshShaderCache lineShaders_;
clang format

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/include/modules/plotting/properties/categoricalaxisproperty.h
> +    const std::vector<std::string>& getCategories() const { return categories_; }
move to cpp file

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/include/modules/plotting/properties/marginproperty.h
> +	 */
clang format

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/include/modules/plotting/properties/plottextproperty.h
> +    FloatProperty rotation_;  //!< Degrees of rotation
consider `// rotation [degrees]` or `// rotation in degrees`
maybe mention that 0 degree means horizontal/regular text direction

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/include/modules/plotting/utils/axisutils.h
> + * No picking buffer will be generated id pickingId = std::numeric_limits<size_t>::max()
typo "generated **id** pickingId" -> is

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/src/properties/categoricalaxisproperty.cpp
> +
clang format

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/src/properties/categoricalaxisproperty.cpp
> +    : AxisProperty(rhs) {
This one is broken! What about the categories? 
Minor ticks state is fine, since constant.

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/src/properties/marginproperty.cpp
> +    top_.set(top, std::min(top_.getMinValue(), top), std::max(top_.getMaxValue(), top * 1.1f),
why `top * 1.1f`?

2019-02-27 16:51 UTC, martinfalk commented on modules/plotting/src/utils/axisutils.cpp
> -
clang format

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/depends.cmake
> +	InviwoBaseGLModule
clang format :)

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/include/modules/plottinggl/processors/parallelcoordinates/parallelcoordinates.h
>      void updateBrushing();
clang format

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/include/modules/plottinggl/utils/axisrenderer.h
> +	void configureShader(Shader& shader);
clang format

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        .onChange([&]() { autoMargins_.pressButton(); });
clang format

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +    //labelPosition_.onChange([&]() { autoMargins_.pressButton(); });
remove?

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        // Place labels on the left side of axis for the first and right side for the others
`// Place labels on the left side of the first axis and on the right for all other axes`

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        float y = (renderer->getCaptionTextSize().y + handleSize_.get().y + handleCaptionMargin) /
might want to ensure pixel alignment for the labels

2019-02-27 16:51 UTC, martinfalk commented on modules/plottinggl/src/utils/axisrenderer.cpp
> +		// Rotate around center
clang format

2019-02-28 07:09 UTC, petersteneteg requested changes

2019-02-28 07:09 UTC, petersteneteg commented on modules/plotting/include/modules/plotting/properties/categoricalaxisproperty.h
> +class IVW_MODULE_PLOTTING_API CategoricalAxisProperty : public AxisProperty {
The design pattern that is used in our plotting, with composite property settings classes nested into the rendering functionality is a nightmare, and really needs a redesign. This pattern introduces way to strong couplings making code reliability almost impossible.

2019-02-28 07:09 UTC, petersteneteg commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +    for (size_t i = 0; i < enabledAxis.size(); i++) {
this way of setting properties from properties is huge code smell, state should __not__ be duplicated.

2019-02-28 07:09 UTC, petersteneteg commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +    for (auto &p : axisVector_) {
again more state duplication!

2019-02-28 07:47 UTC, petersteneteg commented
I might have a look in this...

2019-02-28 08:13 UTC, petersteneteg commented
I have rebased this now...

2019-02-28 10:41 UTC, ResearchDaniel commented
@petersteneteg you are a bit too fast. Have some changes pending. Wait until I commit

2019-02-28 10:59 UTC, ResearchDaniel commented
@petersteneteg I have commited the changes I had so you can take a look now. I think that there are quite some changes that can be made to the design but many of them also involve writing version updaters, which I was not too eager to do at this stage since we might be redesigning the brushing and linking anyway.

2019-02-28 11:03 UTC, petersteneteg commented
ok, cherry pick that one, thanks...

2019-02-28 11:03 UTC, closed without merging

2019-02-28 12:01 UTC, ResearchDaniel commented
I’ll be back on Monday so we can discuss further.

2019-03-01 02:33 UTC, ResearchDaniel commented
A side note: It would probably be a good idea to use features from our GLUI, such as range sliders for the vertical axes. Downside being that the axis labels would need to be integrated somehow.