BrushingAndLinking: Fixed a bug where the column selection would not …
inviwo/inviwo pull request #453
Opened 2019-03-14 12:19 UTC by Alboin

…run if the local selection cache was empty, but the remote set with selected indices was not. This lead to that if an index was selected from another processor the isColumnSelected(index) would return true, but when a sendColumnSelectionEvent({ }) was called to deselect it nothing happened.

Perhaps this should be done for sendSelectionEvent() and sendFilterEvent() as well?

2019-03-14 12:50 UTC, r-englund requested changes
Since the manager is using an IndexList for the filter events we do not need this fix for the FilterEvents, but for the other events we would need this fix.

2019-03-14 12:50 UTC, r-englund commented on modules/brushingandlinking/src/ports/brushingandlinkingports.cpp
> +    if (selectionColumnCache_.size() == 0 && indices.size() == 0 && remoteSelections.size() == 0) return;
use '.empty()' instead of '.size() == 0'

2019-03-14 13:14 UTC, ResearchDaniel approved these changes
Looks good to me. You probably want to incorporate @r-englund suggestions

2019-03-14 13:15 UTC, ResearchDaniel commented
Also, if it means that there are bugs in the other ones too, then fix them as well :)

2019-03-14 14:13 UTC, r-englund approved these changes

2019-03-17 17:14 UTC, petersteneteg requested changes
This should be reformatted, the if needs a pair of braces. We don't allow ifs with a single hanging line in out style guide.

Why is selection Cache and column selection caches mixed?

2019-03-18 07:50 UTC, Alboin commented
> This should be reformatted, the if needs a pair of braces. We don't allow ifs with a single hanging line in out style guide.

Didn't know that! It's been updated with braces now :)
> 
> Why is selection Cache and column selection caches mixed?

Good question! Cleared up the mix-up.

2019-03-18 13:02 UTC, petersteneteg approved these changes

2019-03-18 13:03 UTC, merged