Add world up dropdown for fixUp in trackball
inviwo/inviwo pull request #477
Opened 2019-04-01 08:03 UTC by xeTaiz

The trackball changes in #422 bringt the option to fix horizontal rotations around the world up axis. However I forgot a way to specify the up axis (x, y or z). This adds a dropdown to specify the axis used, defaulting to y.

2019-04-01 09:11 UTC, r-englund requested changes
Do we also want negative x/y/z axis as possible up vectors? And I can also see usecases where a custom up axis is enforced. (For example: My lines in the ventricle has a perceived up-axis that is not aligned with any of the world-axes)

2019-04-01 09:11 UTC, r-englund commented on src/core/interaction/trackball.cpp
> +    worldUp_.setSelectedIndex(1);
default selected index can be set as the 4th argument in the constructor 
https://github.com/inviwo/inviwo/blob/23770f502f7a2596eb34f43286f21216fdd57750/include/inviwo/core/properties/optionproperty.h#L121-L125

2019-04-01 09:11 UTC, r-englund commented on src/core/interaction/trackball.cpp
> +        case 2: return vec3(0,2,0);
shouldn't case 2 be vec3(0,0,1) ?

2019-04-08 14:02 UTC, xeTaiz commented
Oops, sorry I missed your reply :D
I added the changes you wanted and did some property visibility cleanup.

2019-04-08 14:06 UTC, r-englund approved these changes

2019-04-10 07:28 UTC, merged