Feature/image channel split
inviwo/inviwo pull request #526
Opened 2019-05-24 13:34 UTC by VisComKreiser

added processors to split, combine, and replicate image channels.

2019-05-24 13:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inviwo/inviwo?pullRequest=526) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/inviwo/inviwo?pullRequest=526) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inviwo/inviwo?pullRequest=526) it.</sub>

2019-05-27 09:03 UTC, martinfalk requested changes
I'd rather have a processor similar to `VolumeCombiner` which takes a statement like `vec4(img1.rr, img1.aa)` with a multi inport. Not to forget that `Layer` already features a swizzle mask.

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/glsl/img_channel_combine.frag
> +    float r = texture(inport0Color, texCoords).r;
why only `.r`? Seems rather limiting.

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/glsl/img_channel_combine.frag
> +    float r = texture(inport0Color, texCoords).r;
another question is, why do need 4 source textures? How about using swizzling?

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/glsl/img_channel_replicate.frag
> +    vec4 color = vec4(vec3(inputColor.r), alpha_);
Again, why only 'r' ? Use swizzle! 

https://github.com/inviwo/inviwo/blob/18f116ffe038b80b967c70b01bfb3d988fe2b322/include/inviwo/core/datastructures/image/layer.h#L90-L91

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/glsl/img_channel_select.frag
> +    float value = CHANNEL;
what is `CHANNEL`? Why not sample the input texture `inport_` and access it using swizzling?
i.e. `texture(inport_, texCoords).CHANNEL` or `texture(inport_, texCoords)[CHANNEL]`

At least predefine `CHANNEL` if it does not exist, otherwise the shader will not compile.

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/include/modules/basegl/processors/imageprocessing/imagechannelcombine.h
> + *   * __inport0__ Red input image
So in order to recombine a 4 channel image, one has to split it up into 4 separate images with four processors and then use this one to recombine?

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/include/modules/basegl/processors/imageprocessing/imagechannelcombine.h
> + *   * __inport0__ Red input image
Really weird to have 4 inports, one for each channel.

I'd rather have a processor similar to `VolumeCombiner` with a multi inport.

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/include/modules/basegl/processors/imageprocessing/imagechannelreplicate.h
> + * Replicates the selected image channel and creates a 4 channel texture with the selected alpha value.
**What** is replicated, does not state it's only the red channel!  Swizzling!

I'd rather have a processor similar to `VolumeCombiner` with a multi inport.

2019-05-27 09:03 UTC, martinfalk commented on modules/basegl/include/modules/basegl/processors/imageprocessing/imagechannelselect.h
> +    OptionPropertyString channelSelector_; //!< Selection between RED, GREEN, BLUE, and ALPHA
And how would I create a `red, alpha` image?

2019-05-27 09:31 UTC, martinfalk requested changes
What happens to picking buffer and depth buffer of the split/merged images?
Furthermore, an image can have more than one color layer. How is that handled?

2019-05-27 09:31 UTC, martinfalk commented on modules/basegl/src/processors/imageprocessing/imagechannelcombine.cpp
> +        if (inport0_.getData()->getDimensions() != inport1_.getData()->getDimensions() ||
Why is this check necessary? The textures are sample on the GPU anyway.

2019-05-27 09:31 UTC, martinfalk commented on modules/basegl/src/processors/imageprocessing/imagechannelcombine.cpp
> +            auto img = std::make_shared<Image>(dimensions, DataVec4UInt8::get());
This is not good! Why is the image format hard coded here? Either use the common denominator of all input formats or at least use the one of the first inport.

2019-06-14 08:21 UTC, r-englund requested changes
I do not understand the reason/usecase for the replicate processor, it just create a copy of the image with the first channel duplicated into the other two channels. This is the purpose of swizzeling. 
I made some suggested changes which uses swizzeling in the split processor and also removed the hardcoded used UInt8 (0dcd403121610bfe3c0ea01c7bd95e3e934bb459)

2019-06-14 08:24 UTC, r-englund commented
Another alternative to the split processor is to have 4 image outports instead of just one. One outport for each channel removing the need for 4 processors. Using a custom made FBO with 4 render targets, one for each channel, we would also only need one draw call to split the image instead of 4

2019-06-26 08:52 UTC, r-englund commented
rebased into #564

2019-06-26 09:08 UTC, closed without merging