Qt: Fix for broken console widget in qt 15.3.0
inviwo/inviwo pull request #615
Opened 2019-07-11 09:25 UTC by r-englund

Just updated to qt 15.3.0 and the Console Widget had the wrong font and looked Terrible 
Before fix:
![broken-logconsole](https://user-images.githubusercontent.com/534670/61038967-3b993e80-a3ce-11e9-9190-ec1ad0d7870a.PNG)
After fix: 
![image](https://user-images.githubusercontent.com/534670/61039218-9fbc0280-a3ce-11e9-8bbb-8b483cd5b553.png)

2019-07-11 11:37 UTC, martinfalk approved these changes
I am very much in favor of the new (fixed) look.

2019-07-11 13:35 UTC, petersteneteg requested changes
The console should have a fixed format font!

2019-07-11 16:39 UTC, martinfalk commented
According to [this](https://support.microsoft.com/en-us/help/90057/microsoft-supplied-monospaced-truetype-fonts), Windows 10 ships Courier New and Lucida sans typewriter.
For some reason, Qt seems to pick Courier as a system default (I presume), which looks horrible. And courier doesn't know about the ellipsis "…" hence the square boxes. Maybe we can tweak it toward Lucida sans typewriter instead (also supports way more unicode characters).

2019-08-08 14:26 UTC, r-englund commented
This is caused by a bug introduced in qt 5.12.3 https://bugreports.qt.io/browse/QTBUG-75648 
I just tried with qt 5.13.1-preview and it seems to be fixed.
I guess it does not make sense for us to try to fix it if it is only broken in one Qt version?

2019-08-08 14:28 UTC, r-englund commented
![image](https://user-images.githubusercontent.com/534670/62711571-92a82880-b9f9-11e9-9afc-bda56a70fdb2.png)

2019-08-08 15:18 UTC, petersteneteg commented
Agree

2019-08-08 15:18 UTC, closed without merging