Fix/deprecated callbacks, #34
inviwo/inviwo pull request #67
Opened 2018-04-10 15:54 UTC by martinfalk

2018-04-10 15:58 UTC, martinfalk commented
It might be possible, that the deprecation warnings are not shown with MSVC due to pre-compiled headers. Had some problems there where warning C4996 was suppressed.

2018-04-10 18:26 UTC, ResearchDaniel approved these changes
Looks good!

2018-04-11 06:24 UTC, petersteneteg requested changes

2018-04-11 06:24 UTC, petersteneteg commented on include/inviwo/core/ports/inport.h
> +    ivwDeprecatedMethod("const BaseCallBack* onInvalid(std::function<void()> lambda)");
ivwDeprecatedMethod? why not [[deprecated]]?

2018-04-11 06:24 UTC, petersteneteg commented on modules/python3/pybindutils.h
> +#include <warn/push>
Might be nice to put a comment here on why we push/pop...

2018-04-11 06:24 UTC, petersteneteg commented on include/inviwo/core/ports/inport.h
> +    ivwDeprecatedMethod("const BaseCallBack* onInvalid(std::function<void()> lambda)");
also should [[deprecated]] ivwDeprecatedMethod...

2018-04-11 08:07 UTC, martinfalk commented on include/inviwo/core/ports/inport.h
> +    ivwDeprecatedMethod("const BaseCallBack* onInvalid(std::function<void()> lambda)");
forgot to remove `ivwDeprecatedMethod`, `[[deprecated]]` is already in place.

2018-04-11 10:04 UTC, martinfalk commented
requested changes have been fixed

2018-04-11 12:09 UTC, petersteneteg approved these changes

2018-04-11 12:14 UTC, merged