Feature/plottting fixes
inviwo/inviwo pull request #743
Opened 2019-10-08 12:19 UTC by martinfalk

Some fixes regarding plotting issues
* `getVisible()` overload in axis settings caused axis properties to disappear/go to hidden
* pcp and axis properties caused recursive re-evaluations of the network since they invalidate the processor
* VolumeAxis: added range mode for basis + offset

2019-10-08 12:23 UTC, martinfalk commented
Recursing network evaluation caused by adding the highlighted connection. Note that `Cryo Data Fusion` is above the PCP processor. But there is no change on the outport of `Cryo Data Fusion`.
![image](https://user-images.githubusercontent.com/9251300/66395120-f1c4f200-e9d6-11e9-9039-4b2d9ac0cf1e.png)

![image](https://user-images.githubusercontent.com/9251300/66395000-b5919180-e9d6-11e9-9d57-c7123f5e3317.png)

2019-10-08 14:01 UTC, ResearchDaniel requested changes
Have you tried it with a DataFrame that removes/adds columns? 
We need to compare the actual objects in that case, or at least the columns

2019-10-08 14:01 UTC, ResearchDaniel commented on modules/dataframe/include/inviwo/dataframe/datastructures/column.h
> +    TemplateColumn(const std::string &header, std::shared_ptr<Buffer<T>> buffer = nullptr);
Default parameter should be 
std::make_shared<Buffer<T>>()

2019-10-08 14:01 UTC, ResearchDaniel commented on modules/dataframe/src/properties/dataframecolormapproperty.cpp
> +    if (dataframe_ == dataframe) return;
What if the data frame has changed?

2019-10-08 14:01 UTC, ResearchDaniel commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        if (dataframeCached_ == dataFrame_.getData()) return;
What if the DataFrame has new columns?

2019-10-08 14:56 UTC, petersteneteg requested changes

2019-10-08 14:56 UTC, petersteneteg commented on modules/dataframe/src/properties/dataframecolormapproperty.cpp
> +    if (dataframe_ == dataframe) return;
Since dataframe_ can be mutated above in the network, this does not mean that it hasn't changed, hence this seems quite error prone...

2019-10-08 14:56 UTC, petersteneteg commented on modules/dataframe/src/properties/dataframeproperty.cpp
> +    if (dataframe_ == dataframe) return;
Same as above...

2019-10-08 14:56 UTC, petersteneteg commented on modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
> +        if (dataframeCached_ == dataFrame_.getData()) return;
Same as above this does not mean that it has the same cols, rows etc...

2019-10-08 14:56 UTC, petersteneteg commented on modules/plottinggl/src/processors/parallelcoordinates/pcpaxissettings.cpp
> +    if (col_ == col) return;
same here, pointer comparisons are dangerous

2019-10-09 09:24 UTC, martinfalk commented on modules/dataframe/include/inviwo/dataframe/datastructures/column.h
> +    TemplateColumn(const std::string &header, std::shared_ptr<Buffer<T>> buffer = nullptr);
Why? Then we need to check inside the constructor whether `typename T` matches the column buffer type.

2019-10-23 16:58 UTC, closed without merging