Core: Serialize SerializationMode, fixes #839
inviwo/inviwo pull request #843
Opened 2020-01-23 16:33 UTC by r-englund

Serialize SerializationMode, fixes #839

2020-01-23 18:31 UTC, ResearchDaniel commented
I think we need to add documentation on what the different modes do.
enum class PropertySerializationMode { Default = 0, All, None };

2020-01-24 07:38 UTC, petersteneteg requested changes
Why do we need any on change callback for this?

2020-01-24 07:42 UTC, petersteneteg requested changes

2020-01-24 07:42 UTC, petersteneteg commented on include/inviwo/core/properties/property.h
> +    ValueWrapper<PropertySerializationMode> serializationMode_;
make no sense to put this in a value wrapper

2020-01-24 07:42 UTC, petersteneteg commented on include/inviwo/core/processors/compositeprocessor.h
> +    virtual void onSetSerializationMode(Property* property,
why?

2020-01-24 07:42 UTC, petersteneteg commented on include/inviwo/core/properties/propertyobserver.h
> +#include <inviwo/core/properties/valuewrapper.h>
why

2020-01-24 07:42 UTC, petersteneteg commented on src/core/processors/compositeprocessor.cpp
> +    if (auto superProperty = getSuperProperty(orgProp)) {
why? how will this interact with line 274? that is the reasoning here?

2020-01-24 08:29 UTC, closed without merging

2020-01-24 08:30 UTC, r-englund commented
I'll reopen this when I get the time