Python: Export VolumeSequence
inviwo/inviwo pull request #937
Opened 2020-05-14 11:40 UTC by petersteneteg

2020-05-14 11:52 UTC, ResearchDaniel submitted a review, later dismissed

2020-05-14 17:33 UTC, AnkeAnke requested changes
It does not yet solve the problem of process and initialize not being called on the `Failing Example` in the [example branch](https://github.com/inviwo/inviwo/tree/wip/weird-py-behavior).

2020-05-15 05:45 UTC, petersteneteg commented
@AnkeAnke Are you sure? It work for me. Remember that you have to connect the outport to a sink for the process etc to run...

2020-05-15 11:49 UTC, AnkeAnke commented
You're right, it works :)
Seems to have been an error on my side, just worked now (probably forgot to compile the changes in).

2020-05-15 11:50 UTC, AnkeAnke approved these changes

2020-05-15 11:50 UTC, merged