Ordinalrefproperty
inviwo/inviwo pull request #940
Opened 2020-05-15 17:15 UTC by petersteneteg

Like ordinal property but with a get and set callback for the value.

2020-05-15 19:03 UTC, ResearchDaniel requested changes
Looks good. Might be a bug in serialization though

2020-05-15 19:03 UTC, ResearchDaniel commented on include/inviwo/core/properties/ordinalrefproperty.h
> +    minConstraint_.serialize(s, this->serializationMode_);
value must be serialized/deserialized?

2020-05-15 19:03 UTC, ResearchDaniel commented on include/inviwo/core/properties/ordinalrefproperty.h
> + * A property representing a Ordinal value, for example int, floats.
an Ordinal
Also state its difference to OrdinalProperty

2020-05-15 19:03 UTC, ResearchDaniel commented on src/core/common/inviwocore.cpp
> +    util::for_each_type<OrdinalTypes>{}(OrdinalReghelper{}, *this);
Might need to update the json module for the new properties as well

2020-05-15 19:47 UTC, petersteneteg commented on include/inviwo/core/properties/ordinalrefproperty.h
> +    minConstraint_.serialize(s, this->serializationMode_);
no the value is kept external to the property

2020-05-16 07:57 UTC, ResearchDaniel commented on include/inviwo/core/properties/ordinalrefproperty.h
> +    minConstraint_.serialize(s, this->serializationMode_);
But how will the external thingy know about serialization?

2020-05-16 12:32 UTC, petersteneteg commented on include/inviwo/core/properties/ordinalrefproperty.h
> +    minConstraint_.serialize(s, this->serializationMode_);
well it is up to the external thing to persist it state. maybe the processor serialise it or maybe the thing is serialisable it self.

2020-05-18 11:59 UTC, ResearchDaniel submitted a review, later dismissed

2020-05-19 06:15 UTC, ResearchDaniel requested changes
We need converters to link them with OrdinalProperty?
Also forgot that they need to be registered in the webbrowser module, sorry

2020-05-19 06:15 UTC, ResearchDaniel commented on include/inviwo/core/properties/ordinalrefproperty.h
> +    if (auto prop = dynamic_cast<const OrdinalRefProperty<T>*>(srcProperty)) {
Is this tio restrictive? Should we make it possible to also combine this one with OrdinalProperty and vice versa?

2020-05-19 09:57 UTC, petersteneteg commented on include/inviwo/core/properties/ordinalrefproperty.h
> +    if (auto prop = dynamic_cast<const OrdinalRefProperty<T>*>(srcProperty)) {
Added the converters

2020-05-19 10:47 UTC, ResearchDaniel approved these changes

2020-05-19 11:32 UTC, merged