Fixing gcc/clang warnings
inviwo/inviwo pull request #965
Opened 2020-06-18 13:25 UTC by AnkeAnke

Mostly unused variable and redundant move.
Export of specialized template classes failed on clang (silently) gcc.
Tested on gcc-7/Ubuntu 20 (Pop! OS) and MSVC 14/Windows 10 (and clang/jenkins).

2020-06-18 14:44 UTC, petersteneteg submitted a review, later dismissed

2020-06-18 15:12 UTC, r-englund commented on modules/dataframe/src/datastructures/dataframe.cpp
> +    for (const auto &col : df.columns_) {
Need to `clear` `columns_` on `this` first. 
Also, need to check such that `this != *df`

2020-06-18 15:17 UTC, r-englund requested changes

2020-06-18 15:17 UTC, r-englund commented on modules/dataframe/src/datastructures/dataframe.cpp
> +DataFrame &DataFrame::operator=(const DataFrame &&df) {
move ctor and assign-op take non-const input or else you cant move out data from the rhs

2020-06-18 15:17 UTC, r-englund commented on modules/dataframe/src/datastructures/dataframe.cpp
> +DataFrame &DataFrame::operator=(const DataFrame &&df) {
Also, I think the move ctor and assign-op could use `= default`

2020-06-22 12:25 UTC, petersteneteg commented on modules/dataframe/src/datastructures/dataframe.cpp
> +    if (this == &df) return;
should always return *this...

2020-06-22 15:19 UTC, AnkeAnke commented on modules/dataframe/src/datastructures/dataframe.cpp
> +DataFrame &DataFrame::operator=(const DataFrame &&df) {
Fixed the first. Movign the std vector is more efficient than copying, thus the move overrides.

2020-06-23 04:56 UTC, r-englund submitted a review, later dismissed

2020-06-23 08:57 UTC, petersteneteg approved these changes

2020-06-23 08:58 UTC, merged